# 9 WorkFlow Analista Jr

### 9.1 Objetivo

Presentar un workflow/pipeline completo al que los estudiantes deberán
<br>El Analista Jr corre sus scripts en la virtual manchine **desktop-jr** que tiene estas características


*   Normal, paga tarifa completa, nunca es apagada por Google
*   reside en el datacenter de Sao Paulo, Brasil
*   64 GB de memoria RAM
*   8 vCPU

## 9.3  Workflow

## Inicializacion

Esta parte se debe correr con el runtime en lenguaje **R** Ir al menu, Runtime -> Change Runtime Type -> Runtime type -> R

limpio el ambiente de R

In [1]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Thu Aug 14 10:17:56 AM 2025"

In [2]:
# limpio la memoria
rm(list=ls(all.names=TRUE)) # remove all objects
gc(full=TRUE, verbose=FALSE) # garbage collection

       used    (Mb) gc trigger (Mb) max used (Mb)
Ncells  657824 35.2 1443137    77.1 1443137  77.1
Vcells 1212826  9.3 8388608    64.0 1928907  14.8

In [3]:
require("data.table")

if( !require("R.utils")) install.packages("R.utils")
require("R.utils")

Loading required package: data.table

Loading required package: R.utils

Loading required package: R.oo

Loading required package: R.methodsS3

R.methodsS3 v1.8.2 (2022-06-13 22:00:14 UTC) successfully loaded. See ?R.methodsS3 for help.

R.oo v1.27.1 (2025-05-02 21:00:05 UTC) successfully loaded. See ?R.oo for help.


Attaching package: 'R.oo'


The following object is masked from 'package:R.methodsS3':

    throw


The following objects are masked from 'package:methods':

    getClasses, getMethods


The following objects are masked from 'package:base':

    attach, detach, load, save


R.utils v2.13.0 (2025-02-24 21:20:02 UTC) successfully loaded. See ?R.utils for help.


Attaching package: 'R.utils'


The following object is masked from 'package:utils':

    timestamp


The following objects are masked from 'package:base':

    cat, commandArgs, getOption, isOpen, nullfile, parse, use, warnings

#### Parametros

In [4]:
PARAM <- list()
PARAM$semilla_primigenia <- 100151

PARAM$experimento <- 9106
PARAM$dataset <- "analistajr_competencia_2025.csv.gz"

### 9.3.1   Preprocesamiento del dataset

#### 9.3.1.1  DT incorporar dataset

In [5]:
library(data.table)

dataset <- fread(
  "C:/Users/Luis/Documents/dm2025/Experimento colaborativo FEHistorico/datasets_analistajr_competencia_2025.csv.gz",
  encoding = "UTF-8"
)

print(dim(dataset))
print(head(dataset))

[1] 976374     55
   numero_de_cliente foto_mes internet cliente_edad cliente_antiguedad
               <int>    <int>    <int>        <int>              <int>
1:          29187730   201901        1           62                296
2:          29187961   201901        1           59                296
3:          29193101   201901        1           66                349
4:          29193281   201901        1           52                142
5:          29198891   201901        1           53                296
6:          29200770   201901        1           56                246
   mrentabilidad mrentabilidad_annual mcomisiones mactivos_margen
           <num>                <num>       <num>           <num>
1:      14301.42             43997.41     8970.82        -1262.22
2:       7542.75             34281.62     1960.95          -46.22
3:       5749.83             29663.24     4745.47        -3592.97
4:      12742.79             43614.97    12275.05         -718.19
5:       4237.90             23234.30     1176.26         -680.91
6:      12527.87             60467.54     8240.80          281.61
   mpasivos_margen cproductos mcuenta_corriente mcaja_ahorro
             <num>      <int>             <num>        <num>
1:         5806.64          8              0.00     96092.69
2:         4804.79          7              0.00    137510.70
3:         4449.20          9              0.00     24713.87
4:         1116.94         10              0.00      4491.28
5:         3291.01          6              0.00     61706.66
6:         3373.18         10          15169.65    104037.83
   cdescubierto_preacordado mcuentas_saldo ctarjeta_visa
                      <int>          <num>         <int>
1:                        1      345700.67             1
2:                        1      122088.96             1
3:                        1      126250.20             1
4:                        1      107490.65             1
5:                        1       76287.69             1
6:                        1      126230.06             1
   ctarjeta_visa_transacciones mtarjeta_visa_consumo ctarjeta_master
                         <int>                 <num>           <int>
1:                          57             148183.89               1
2:                          45              56482.69               1
3:                          31              32369.28               1
4:                           7              19984.36               1
5:                           4              26750.83               1
6:                           9              10343.40               1
   ctarjeta_master_transacciones mtarjeta_master_consumo cprestamos_personales
                           <int>                   <num>                 <int>
1:                             0                    0.00                     0
2:                             2                 7845.04                     0
3:                            30               159870.23                     2
4:                             5                 8034.05                     0
5:                             3                 9564.64                     0
6:                             2                 1067.32                     0
   mprestamos_personales cpayroll_trx  mpayroll
                   <num>        <int>     <num>
1:                   0.0            1 109769.34
2:                   0.0            0      0.00
3:               64821.7            0      0.00
4:                   0.0            0      0.00
5:                   0.0            0      0.00
6:                   0.0            1  70846.46
   mttarjeta_visa_debitos_automaticos ccomisiones_mantenimiento
                                <num>                     <int>
1:                           16406.22                         1
2:                            7447.01                         1
3:                            3620.15                         1
4:                           19346.69                         1
5:                           22586.68                         1
6:                            5546.78                         1
   mcomisiones_mantenimiento ccomisiones_otras mtransferencias_recibidas
                       <num>             <int>                     <num>
1:                     53.95                 8                         0
2:                   1020.77                12                         0
3:                   1199.97                14                         0
4:                    723.51                36                         0
5:                    723.51                 6                         0
6:                     15.01                16                         0
   ccallcenter_transacciones thomebanking chomebanking_transacciones
                       <int>        <int>                      <int>
1:                         0            1                         87
2:                         0            1                         21
3:                         2            1                        136
4:                         0            0                          0
5:                         0            1                          0
6:                         0            1                         19
   ctrx_quarter Master_status Master_mfinanciacion_limite Master_Fvencimiento
          <int>         <int>                       <num>               <int>
1:          174             0                    412395.4               -1276
2:          139             0                    349933.8               -1519
3:          258             0                    207286.7               -1398
4:           87             0                     50673.6               -1398
5:           38             0                     38005.2               -1337
6:          145             0                    205263.7               -1488
   Master_msaldototal Master_mlimitecompra Master_fultimo_cierre
                <num>                <num>                 <int>
1:               0.00             458226.8                     1
2:            7817.57             388815.4                    15
3:          189401.33             230318.5                     8
4:            8130.46              56304.0                     1
5:            9564.64              42228.0                     1
6:            1067.32             228070.8                     1
   Master_fechaalta Master_mconsumototal Master_cconsumos Master_mpagominimo
              <int>                <num>            <int>              <num>
1:             6793                   NA               NA               0.00
2:             5453              7845.04                2             281.52
3:             1540            158126.67               24            9794.55
4:             2639              8034.05                5             410.55
5:             6716              9564.64                3             375.36
6:             4362               187.68                1              93.84
   Visa_status Visa_mfinanciacion_limite Visa_Fvencimiento Visa_msaldototal
         <int>                     <num>             <int>            <num>
1:           0                  412896.5             -1337        127146.16
2:           0                  412395.4             -1915         47726.51
3:           0                  207286.7             -1763         62541.14
4:           0                   38005.2             -1154         17241.41
5:           0                   50673.6              -211         22805.49
6:           0                  416459.8             -1763          8826.08
   Visa_mlimitecompra Visa_fultimo_cierre Visa_fechaalta Visa_mconsumototal
                <num>               <int>          <int>              <num>
1:           458783.6                  22           5604          122057.93
2:           458226.8                   1           7604           48761.71
3:           230318.5                   8           1540           26574.05
4:            42228.0                   1           2864           19809.29
5:            56304.0                   1           6756           26750.83
6:           462742.9                   8           4474            5590.22
   Visa_cconsumos Visa_mpagominimo clase_ternaria
            <int>            <num>         <char>
1:             50         11190.42       CONTINUA
2:             41          2087.94       CONTINUA
3:             22          5841.54       CONTINUA
4:              8          1032.24       CONTINUA
5:              4          1067.43       CONTINUA
6:              5          1736.04       CONTINUA

#### 9.3.1.2  CA  Catastrophe Analysis
Se intentan reparar las variables que para un mes están con todos los valores en cero.

El método que se utiliza es **Machine Learning** se asigna NA also valores, si ha leido bien, es la "anti imputación de valores faltantes"
<br> Usted podrá aplicar aquí otros métodos

In [6]:
if( !require("mice")) install.packages("mice", repos = "http://cran.us.r-project.org")
require("mice")

Loading required package: mice


Attaching package: 'mice'


The following object is masked from 'package:stats':

    filter


The following objects are masked from 'package:base':

    cbind, rbind

In [7]:
# Escrito por alumnos de  Universidad Austral  Rosario

Corregir_MICE <- function(pcampo, pmeses) {

  meth <- rep("", ncol(dataset))
  names(meth) <- colnames(dataset)
  meth[names(meth) == pcampo] <- "sample"

  # llamada a mice  !
  imputacion <- mice(dataset,
    method = meth,
    maxit = 5,
    m = 1,
    seed = 7)

  tbl <- mice::complete(dataset)

  dataset[, paste0(pcampo) := ifelse(foto_mes %in% pmeses, tbl[, get(pcampo)], get(pcampo))]

}

In [8]:
Corregir_interpolar <- function(pcampo, pmeses) {

  tbl <- dataset[, list(
    "v1" = shift(get(pcampo), 1, type = "lag"),
    "v2" = shift(get(pcampo), 1, type = "lead")
  ),
  by = eval(envg$PARAM$dataset_metadata$entity_id)
  ]

  tbl[, paste0(envg$PARAM$dataset_metadata$entity_id) := NULL]
  tbl[, promedio := rowMeans(tbl, na.rm = TRUE)]

  dataset[
    ,
    paste0(pcampo) := ifelse(!(foto_mes %in% pmeses),
      get(pcampo),
      tbl$promedio
    )
  ]
}

In [9]:
AsignarNA_campomeses <- function(pcampo, pmeses) {

  if( pcampo %in% colnames( dataset ) ) {

    dataset[ foto_mes %in% pmeses, paste0(pcampo) := NA ]
  }
}

In [10]:

Corregir_atributo <- function(pcampo, pmeses, pmetodo)
{
  # si el campo no existe en el dataset, Afuera !
  if( !(pcampo %in% colnames( dataset )) )
    return( 1 )

  # llamo a la funcion especializada que corresponde
  switch( pmetodo,
    "MachineLearning"     = AsignarNA_campomeses(pcampo, pmeses),
    "EstadisticaClasica"  = Corregir_interpolar(pcampo, pmeses),
    "MICE"                = Corregir_MICE(pcampo, pmeses),
  )

  return( 0 )
}

In [11]:

Corregir_Rotas <- function(dataset, pmetodo) {
  gc(verbose= FALSE)
  cat( "inicio Corregir_Rotas()\n")
  # acomodo los errores del dataset

  Corregir_atributo("active_quarter", c(202006), pmetodo) # 1
  Corregir_atributo("internet", c(202006), pmetodo) # 2

  Corregir_atributo("mrentabilidad", c(201905, 201910, 202006), pmetodo) # 3
  Corregir_atributo("mrentabilidad_annual", c(201905, 201910, 202006), pmetodo) # 4

  Corregir_atributo("mcomisiones", c(201905, 201910, 202006), pmetodo) # 5

  Corregir_atributo("mactivos_margen", c(201905, 201910, 202006), pmetodo) # 6
  Corregir_atributo("mpasivos_margen", c(201905, 201910, 202006), pmetodo) # 7

  Corregir_atributo("mcuentas_saldo", c(202006), pmetodo) # 8

  Corregir_atributo("ctarjeta_debito_transacciones", c(202006), pmetodo) # 9

  Corregir_atributo("mautoservicio", c(202006), pmetodo) # 10

  Corregir_atributo("ctarjeta_visa_transacciones", c(202006), pmetodo) # 11
  Corregir_atributo("mtarjeta_visa_consumo", c(202006), pmetodo) # 12

  Corregir_atributo("ctarjeta_master_transacciones", c(202006), pmetodo) # 13
  Corregir_atributo("mtarjeta_master_consumo", c(202006), pmetodo) # 14

  Corregir_atributo("ctarjeta_visa_debitos_automaticos", c(201904), pmetodo) # 15
  Corregir_atributo("mttarjeta_visa_debitos_automaticos", c(201904), pmetodo) # 16

  Corregir_atributo("ccajeros_propios_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 17

  Corregir_atributo("mcajeros_propios_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 18

  Corregir_atributo("ctarjeta_visa_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 19

  Corregir_atributo("mtarjeta_visa_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 20

  Corregir_atributo("ctarjeta_master_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 21

  Corregir_atributo("mtarjeta_master_descuentos",
    c(201910, 202002, 202006, 202009, 202010, 202102), pmetodo) # 22

  Corregir_atributo("ccomisiones_otras", c(201905, 201910, 202006), pmetodo) # 23
  Corregir_atributo("mcomisiones_otras", c(201905, 201910, 202006), pmetodo) # 24

  Corregir_atributo("cextraccion_autoservicio", c(202006), pmetodo) # 25
  Corregir_atributo("mextraccion_autoservicio", c(202006), pmetodo) # 26

  Corregir_atributo("ccheques_depositados", c(202006), pmetodo) # 27
  Corregir_atributo("mcheques_depositados", c(202006), pmetodo) # 28
  Corregir_atributo("ccheques_emitidos", c(202006), pmetodo) # 29
  Corregir_atributo("mcheques_emitidos", c(202006), pmetodo) # 30
  Corregir_atributo("ccheques_depositados_rechazados", c(202006), pmetodo) # 31
  Corregir_atributo("mcheques_depositados_rechazados", c(202006), pmetodo) # 32
  Corregir_atributo("ccheques_emitidos_rechazados", c(202006), pmetodo) # 33
  Corregir_atributo("mcheques_emitidos_rechazados", c(202006), pmetodo) # 34

  Corregir_atributo("tcallcenter", c(202006), pmetodo) # 35
  Corregir_atributo("ccallcenter_transacciones", c(202006), pmetodo) # 36

  Corregir_atributo("thomebanking", c(202006), pmetodo) # 37
  Corregir_atributo("chomebanking_transacciones", c(201910, 202006), pmetodo) # 38

  Corregir_atributo("ccajas_transacciones", c(202006), pmetodo) # 39
  Corregir_atributo("ccajas_consultas", c(202006), pmetodo) # 40

  Corregir_atributo("ccajas_depositos", c(202006, 202105), pmetodo) # 41

  Corregir_atributo("ccajas_extracciones", c(202006), pmetodo) # 41
  Corregir_atributo("ccajas_otras", c(202006), pmetodo) # 43

  Corregir_atributo("catm_trx", c(202006), pmetodo) # 44
  Corregir_atributo("matm", c(202006), pmetodo) # 45
  Corregir_atributo("catm_trx_other", c(202006), pmetodo) # 46
  Corregir_atributo("matm_other", c(202006), pmetodo) # 47

  cat( "fin Corregir_rotas()\n")
}

In [12]:
# resuelvo el Catastrophe Analysis

setorder( dataset, numero_de_cliente, foto_mes )

PARAM$CA$metodo= "MachineLearning"

if( PARAM$CA$metodo %in% c("MachineLearning", "EstadisticaClasica", "MICE") )
  Corregir_Rotas(dataset, PARAM$CA$metodo)

inicio Corregir_Rotas()
fin Corregir_rotas()

#### 9.3.1.3  DR  Data Drifting
Se intenta corregir el data drifting, ajustando por algunos indices financieros

In [13]:
# meses que me interesan para el ajuste de variables monetarias
vfoto_mes <- c(
  201901, 201902, 201903, 201904, 201905, 201906,
  201907, 201908, 201909, 201910, 201911, 201912,
  202001, 202002, 202003, 202004, 202005, 202006,
  202007, 202008, 202009, 202010, 202011, 202012,
  202101, 202102, 202103, 202104, 202105, 202106,
  202107, 202108, 202109
)

In [14]:
# los valores que siguen fueron calculados por alumnos

# momento 1.0  31-dic-2020 a las 23:59
vIPC <- c(
  1.9903030878, 1.9174403544, 1.8296186587,
  1.7728862972, 1.7212488323, 1.6776304408,
  1.6431248196, 1.5814483345, 1.4947526791,
  1.4484037589, 1.3913580777, 1.3404220402,
  1.3154288912, 1.2921698342, 1.2472681797,
  1.2300475145, 1.2118694724, 1.1881073259,
  1.1693969743, 1.1375456949, 1.1065619600,
  1.0681100000, 1.0370000000, 1.0000000000,
  0.9680542110, 0.9344152616, 0.8882274350,
  0.8532444140, 0.8251880213, 0.8003763543,
  0.7763107219, 0.7566381305, 0.7289384687
)

vdolar_blue <- c(
   39.045455,  38.402500,  41.639474,
   44.274737,  46.095455,  45.063333,
   43.983333,  54.842857,  61.059524,
   65.545455,  66.750000,  72.368421,
   77.477273,  78.191667,  82.434211,
  101.087500, 126.236842, 125.857143,
  130.782609, 133.400000, 137.954545,
  170.619048, 160.400000, 153.052632,
  157.900000, 149.380952, 143.615385,
  146.250000, 153.550000, 162.000000,
  178.478261, 180.878788, 184.357143
)

vdolar_oficial <- c(
   38.430000,  39.428000,  42.542105,
   44.354211,  46.088636,  44.955000,
   43.751429,  54.650476,  58.790000,
   61.403182,  63.012632,  63.011579,
   62.983636,  63.580556,  65.200000,
   67.872000,  70.047895,  72.520952,
   75.324286,  77.488500,  79.430909,
   83.134762,  85.484737,  88.181667,
   91.474000,  93.997778,  96.635909,
   98.526000,  99.613158, 100.619048,
  101.619048, 102.569048, 103.781818
)

vUVA <- c(
  2.001408838932958,  1.950325472789153,  1.89323032351521,
  1.8247220405493787, 1.746027787673673,  1.6871348409529485,
  1.6361678865622313, 1.5927529755859773, 1.5549162794128493,
  1.4949100586391746, 1.4197729500774545, 1.3678188186372326,
  1.3136508617223726, 1.2690535173062818, 1.2381595983200178,
  1.211656735577568,  1.1770808941405335, 1.1570338657445522,
  1.1388769475653255, 1.1156993751209352, 1.093638313080772,
  1.0657171590878205, 1.0362173587708712, 1.0,
  0.9669867858358365, 0.9323750098728378, 0.8958202912590305,
  0.8631993702994263, 0.8253893405524657, 0.7928918905364516,
  0.7666323845128089, 0.7428976357662823, 0.721615762047849
)

In [15]:
tb_indices <- as.data.table( list(
  "IPC" = vIPC,
  "dolar_blue" = vdolar_blue,
  "dolar_oficial" = vdolar_oficial,
  "UVA" = vUVA
  )
)

tb_indices[[ 'foto_mes' ]] <- vfoto_mes

tb_indices

   IPC       dolar_blue dolar_oficial UVA       foto_mes
1  1.9903031  39.04545   38.43000     2.0014088 201901
2  1.9174404  38.40250   39.42800     1.9503255 201902
3  1.8296187  41.63947   42.54210     1.8932303 201903
4  1.7728863  44.27474   44.35421     1.8247220 201904
5  1.7212488  46.09546   46.08864     1.7460278 201905
6  1.6776304  45.06333   44.95500     1.6871348 201906
7  1.6431248  43.98333   43.75143     1.6361679 201907
8  1.5814483  54.84286   54.65048     1.5927530 201908
9  1.4947527  61.05952   58.79000     1.5549163 201909
10 1.4484038  65.54546   61.40318     1.4949101 201910
11 1.3913581  66.75000   63.01263     1.4197730 201911
12 1.3404220  72.36842   63.01158     1.3678188 201912
13 1.3154289  77.47727   62.98364     1.3136509 202001
14 1.2921698  78.19167   63.58056     1.2690535 202002
15 1.2472682  82.43421   65.20000     1.2381596 202003
16 1.2300475 101.08750   67.87200     1.2116567 202004
17 1.2118695 126.23684   70.04789     1.1770809 202005
18 1.1881073 125.85714   72.52095     1.1570339 202006
19 1.1693970 130.78261   75.32429     1.1388769 202007
20 1.1375457 133.40000   77.48850     1.1156994 202008
21 1.1065620 137.95454   79.43091     1.0936383 202009
22 1.0681100 170.61905   83.13476     1.0657172 202010
23 1.0370000 160.40000   85.48474     1.0362174 202011
24 1.0000000 153.05263   88.18167     1.0000000 202012
25 0.9680542 157.90000   91.47400     0.9669868 202101
26 0.9344153 149.38095   93.99778     0.9323750 202102
27 0.8882274 143.61539   96.63591     0.8958203 202103
28 0.8532444 146.25000   98.52600     0.8631994 202104
29 0.8251880 153.55000   99.61316     0.8253893 202105
30 0.8003764 162.00000  100.61905     0.7928919 202106
31 0.7763107 178.47826  101.61905     0.7666324 202107
32 0.7566381 180.87879  102.56905     0.7428976 202108
33 0.7289385 184.35714  103.78182     0.7216158 202109

In [16]:
drift_UVA <- function(campos_monetarios) {
  cat( "inicio drift_UVA()\n")

  dataset[tb_indices,
    on = c("foto_mes"),
    (campos_monetarios) := .SD * i.UVA,
    .SDcols = campos_monetarios
  ]

  cat( "fin drift_UVA()\n")
}

In [17]:
drift_dolar_oficial <- function(campos_monetarios) {
  cat( "inicio drift_dolar_oficial()\n")

  dataset[tb_indices,
    on = c("foto_mes"),
    (campos_monetarios) := .SD / i.dolar_oficial,
    .SDcols = campos_monetarios
  ]

  cat( "fin drift_dolar_oficial()\n")
}

In [18]:
drift_dolar_blue <- function(campos_monetarios) {
  cat( "inicio drift_dolar_blue()\n")

  dataset[tb_indices,
    on = c("foto_mes"),
    (campos_monetarios) := .SD / i.dolar_blue,
    .SDcols = campos_monetarios
  ]

  cat( "fin drift_dolar_blue()\n")
}

In [19]:
drift_deflacion <- function(campos_monetarios) {
  cat( "inicio drift_deflacion()\n")

  dataset[tb_indices,
    on = c("foto_mes"),
    (campos_monetarios) := .SD * i.IPC,
    .SDcols = campos_monetarios
  ]

  cat( "fin drift_deflacion()\n")
}

In [20]:
drift_rank_simple <- function(campos_drift) {

  cat( "inicio drift_rank_simple()\n")
  for (campo in campos_drift)
  {
    cat(campo, " ")
    dataset[, paste0(campo, "_rank") :=
      (frank(get(campo), ties.method = "random") - 1) / (.N - 1), by = list(foto_mes)]
    dataset[, (campo) := NULL]
  }
  cat( "fin drift_rank_simple()\n")
}

In [21]:
# El cero se transforma en cero
# los positivos se rankean por su lado
# los negativos se rankean por su lado

drift_rank_cero_fijo <- function(campos_drift) {

  cat( "inicio drift_rank_cero_fijo()\n")
  for (campo in campos_drift)
  {
    cat(campo, " ")
    dataset[get(campo) == 0, paste0(campo, "_rank") := 0]
    dataset[get(campo) > 0, paste0(campo, "_rank") :=
      frank(get(campo), ties.method = "random") / .N, by = list(foto_mes)]

    dataset[get(campo) < 0, paste0(campo, "_rank") :=
      -frank(-get(campo), ties.method = "random") / .N, by = list(foto_mes)]
    dataset[, (campo) := NULL]
  }
  cat("\n")
  cat( "fin drift_rank_cero_fijo()\n")
}

In [22]:
drift_estandarizar <- function(campos_drift) {

  cat( "inicio drift_estandarizar()\n")
  for (campo in campos_drift)
  {
    cat(campo, " ")
    dataset[, paste0(campo, "_normal") :=
      (get(campo) -mean(campo, na.rm=TRUE)) / sd(get(campo), na.rm=TRUE),
      by = list(foto_mes)]

    dataset[, (campo) := NULL]
  }
  cat( "fin drift_estandarizar()\n")
}

In [23]:
# por como armé los nombres de campos,
#  estos son los campos que expresan variables monetarias
campos_monetarios <- colnames(dataset)
campos_monetarios <- campos_monetarios[campos_monetarios %like%
  "^(m|Visa_m|Master_m|vm_m)"]

campos_monetarios

 [1] "mrentabilidad"                      "mrentabilidad_annual"
 [3] "mcomisiones"                        "mactivos_margen"
 [5] "mpasivos_margen"                    "mcuenta_corriente"
 [7] "mcaja_ahorro"                       "mcuentas_saldo"
 [9] "mtarjeta_visa_consumo"              "mtarjeta_master_consumo"
[11] "mprestamos_personales"              "mpayroll"
[13] "mttarjeta_visa_debitos_automaticos" "mcomisiones_mantenimiento"
[15] "mtransferencias_recibidas"          "Master_mfinanciacion_limite"
[17] "Master_msaldototal"                 "Master_mlimitecompra"
[19] "Master_mconsumototal"               "Master_mpagominimo"
[21] "Visa_mfinanciacion_limite"          "Visa_msaldototal"
[23] "Visa_mlimitecompra"                 "Visa_mconsumototal"
[25] "Visa_mpagominimo"

In [24]:
# ejecuto el Data Drifting
setorder( dataset, numero_de_cliente, foto_mes )


PARAM$DR$metodo <- "deflacion"

switch(PARAM$DR$metodo,
  "ninguno"        = cat("No hay correccion del data drifting"),
  "rank_simple"    = drift_rank_simple(campos_monetarios),
  "rank_cero_fijo" = drift_rank_cero_fijo(campos_monetarios),
  "deflacion"      = drift_deflacion(campos_monetarios),
  "dolar_blue"     = drift_dolarblue(campos_monetarios),
  "dolar_oficial"  = drift_dolaroficial(campos_monetarios),
  "UVA"            = drift_UVA(campos_monetarios),
  "estandarizar"   = drift_estandarizar(campos_monetarios)
)

inicio drift_deflacion()
fin drift_deflacion()

In [25]:
colnames(dataset)

 [1] "numero_de_cliente"                  "foto_mes"
 [3] "internet"                           "cliente_edad"
 [5] "cliente_antiguedad"                 "mrentabilidad"
 [7] "mrentabilidad_annual"               "mcomisiones"
 [9] "mactivos_margen"                    "mpasivos_margen"
[11] "cproductos"                         "mcuenta_corriente"
[13] "mcaja_ahorro"                       "cdescubierto_preacordado"
[15] "mcuentas_saldo"                     "ctarjeta_visa"
[17] "ctarjeta_visa_transacciones"        "mtarjeta_visa_consumo"
[19] "ctarjeta_master"                    "ctarjeta_master_transacciones"
[21] "mtarjeta_master_consumo"            "cprestamos_personales"
[23] "mprestamos_personales"              "cpayroll_trx"
[25] "mpayroll"                           "mttarjeta_visa_debitos_automaticos"
[27] "ccomisiones_mantenimiento"          "mcomisiones_mantenimiento"
[29] "ccomisiones_otras"                  "mtransferencias_recibidas"
[31] "ccallcenter_transacciones"          "thomebanking"
[33] "chomebanking_transacciones"         "ctrx_quarter"
[35] "Master_status"                      "Master_mfinanciacion_limite"
[37] "Master_Fvencimiento"                "Master_msaldototal"
[39] "Master_mlimitecompra"               "Master_fultimo_cierre"
[41] "Master_fechaalta"                   "Master_mconsumototal"
[43] "Master_cconsumos"                   "Master_mpagominimo"
[45] "Visa_status"                        "Visa_mfinanciacion_limite"
[47] "Visa_Fvencimiento"                  "Visa_msaldototal"
[49] "Visa_mlimitecompra"                 "Visa_fultimo_cierre"
[51] "Visa_fechaalta"                     "Visa_mconsumototal"
[53] "Visa_cconsumos"                     "Visa_mpagominimo"
[55] "clase_ternaria"

In [26]:
# se intenta corregir el data drifting utilizando algunos indices financieros

#### 9.3.1.3  FE_intra_manual Feature Engineering intra-mes

Agrego campos nuevos dentro del mismo mes, SIN considerar la historia.

In [27]:
# esta funcion atributos presentes existe debido a que las modalidades poseen datasets con distinta cantidad de campos
atributos_presentes <- function( patributos )
{
  atributos <- unique( patributos )
  comun <- intersect( atributos, colnames(dataset) )

  return(  length( atributos ) == length( comun ) )
}

# el mes 1,2, ..12
if( atributos_presentes( c("foto_mes") ))
  dataset[, kmes := foto_mes %% 100]

# variable extraida de una tesis de maestria de Irlanda
if( atributos_presentes( c("mpayroll", "cliente_edad") ))
  dataset[, mpayroll_sobre_edad := mpayroll / cliente_edad]

In [28]:
# visualizo las columas del dataset a esta etapa
colnames(dataset)

 [1] "numero_de_cliente"                  "foto_mes"
 [3] "internet"                           "cliente_edad"
 [5] "cliente_antiguedad"                 "mrentabilidad"
 [7] "mrentabilidad_annual"               "mcomisiones"
 [9] "mactivos_margen"                    "mpasivos_margen"
[11] "cproductos"                         "mcuenta_corriente"
[13] "mcaja_ahorro"                       "cdescubierto_preacordado"
[15] "mcuentas_saldo"                     "ctarjeta_visa"
[17] "ctarjeta_visa_transacciones"        "mtarjeta_visa_consumo"
[19] "ctarjeta_master"                    "ctarjeta_master_transacciones"
[21] "mtarjeta_master_consumo"            "cprestamos_personales"
[23] "mprestamos_personales"              "cpayroll_trx"
[25] "mpayroll"                           "mttarjeta_visa_debitos_automaticos"
[27] "ccomisiones_mantenimiento"          "mcomisiones_mantenimiento"
[29] "ccomisiones_otras"                  "mtransferencias_recibidas"
[31] "ccallcenter_transacciones"          "thomebanking"
[33] "chomebanking_transacciones"         "ctrx_quarter"
[35] "Master_status"                      "Master_mfinanciacion_limite"
[37] "Master_Fvencimiento"                "Master_msaldototal"
[39] "Master_mlimitecompra"               "Master_fultimo_cierre"
[41] "Master_fechaalta"                   "Master_mconsumototal"
[43] "Master_cconsumos"                   "Master_mpagominimo"
[45] "Visa_status"                        "Visa_mfinanciacion_limite"
[47] "Visa_Fvencimiento"                  "Visa_msaldototal"
[49] "Visa_mlimitecompra"                 "Visa_fultimo_cierre"
[51] "Visa_fechaalta"                     "Visa_mconsumototal"
[53] "Visa_cconsumos"                     "Visa_mpagominimo"
[55] "clase_ternaria"                     "kmes"
[57] "mpayroll_sobre_edad"

#### 9.3.1.4  FE_rf Feature Engineering de nuevas variables a partir de hojas de Random Forest

In [29]:
if( !require("lightgbm")) install.packages("lightgbm")
require("lightgbm")

Loading required package: lightgbm

In [30]:
AgregaVarRandomForest <- function() {

  cat( "inicio AgregaVarRandomForest()\n")
  gc(verbose= FALSE)
  dataset[, clase01 := 0L ]
  dataset[ clase_ternaria %in% PARAM$FE_rf$train$clase01_valor1,
      clase01 := 1L ]

  campos_buenos <- setdiff(
    colnames(dataset),
    c( "clase_ternaria", "clase01")
  )

  dataset[, entrenamiento :=
    as.integer( foto_mes %in% PARAM$FE_rf$train$training )]

  dtrain <- lgb.Dataset(
    data = data.matrix(dataset[entrenamiento == TRUE, campos_buenos, with = FALSE]),
    label = dataset[entrenamiento == TRUE, clase01],
    free_raw_data = FALSE
  )

  modelo <- lgb.train(
     data = dtrain,
     param = PARAM$FE_rf$lgb_param,
     verbose = -100
  )

  cat( "Fin construccion RandomForest\n" )
  # grabo el modelo, achivo .model
  lgb.save(modelo, file="modelo.model" )

  qarbolitos <- copy(PARAM$FE_rf$lgb_param$num_iterations)

  periodos <- dataset[ , unique( foto_mes ) ]

  for( periodo in  periodos )
  {
    cat( "periodo = ", periodo, "\n" )
    datamatrix <- data.matrix(dataset[ foto_mes== periodo, campos_buenos, with = FALSE])

    cat( "Inicio prediccion\n" )
    prediccion <- predict(
        modelo,
        datamatrix,
        type = "leaf"
    )
    cat( "Fin prediccion\n" )

    for( arbolito in 1:qarbolitos )
    {
       cat( arbolito, " " )
       hojas_arbol <- unique(prediccion[ , arbolito])

       for (pos in 1:length(hojas_arbol)) {
         # el numero de nodo de la hoja, estan salteados
         nodo_id <- hojas_arbol[pos]
         dataset[ foto_mes== periodo, paste0(
            "rf_", sprintf("%03d", arbolito),
             "_", sprintf("%03d", nodo_id)
          ) :=  as.integer( nodo_id == prediccion[ , arbolito]) ]

       }

       rm( hojas_arbol )
    }
    cat( "\n" )

    rm( prediccion )
    rm( datamatrix )
    gc(verbose= FALSE)
  }

  gc(verbose= FALSE)

  # borro clase01 , no debe ensuciar el dataset
  dataset[ , clase01 := NULL ]

}

In [31]:
# Parametros de Feature Engineering  a partir de hojas de Random Forest

# Estos CUATRO parametros son los que se deben modificar
PARAM$FE_rf$arbolitos= 20
PARAM$FE_rf$hojas_por_arbol= 16
PARAM$FE_rf$datos_por_hoja= 100
PARAM$FE_rf$mtry_ratio= 0.2

# Estos son quasi fijos
PARAM$FE_rf$train$clase01_valor1 <- c( "BAJA+2", "BAJA+1")
PARAM$FE_rf$train$training <- c( 202101, 202102, 202103)

# Estos TAMBIEN son quasi fijos
PARAM$FE_rf$lgb_param <-list(
    # parametros que se pueden cambiar
    num_iterations = PARAM$FE_rf$arbolitos,
    num_leaves  = PARAM$FE_rf$hojas_por_arbol,
    min_data_in_leaf = PARAM$FE_rf$datos_por_hoja,
    feature_fraction_bynode  = PARAM$FE_rf$mtry_ratio,

    # para que LightGBM emule Random Forest
    boosting = "rf",
    bagging_fraction = ( 1.0 - 1.0/exp(1.0) ),
    bagging_freq = 1.0,
    feature_fraction = 1.0,

    # genericos de LightGBM
    max_bin = 31L,
    objective = "binary",
    first_metric_only = TRUE,
    boost_from_average = TRUE,
    feature_pre_filter = FALSE,
    force_row_wise = TRUE,
    verbosity = -100,
    max_depth = -1L,
    min_gain_to_split = 0.0,
    min_sum_hessian_in_leaf = 0.001,
    lambda_l1 = 0.0,
    lambda_l2 = 0.0,

    pos_bagging_fraction = 1.0,
    neg_bagging_fraction = 1.0,
    is_unbalance = FALSE,
    scale_pos_weight = 1.0,

    drop_rate = 0.1,
    max_drop = 50,
    skip_drop = 0.5,

    extra_trees = FALSE
  )

In [32]:
# Feature Engineering agregando variables de Random Forest
AgregaVarRandomForest()

inicio AgregaVarRandomForest()
Fin construccion RandomForest
periodo =  202003
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202004
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202005
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202006
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202007
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202008
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202009
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202010
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202011
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202012
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202101
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202102
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202103
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202104
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202105
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202106
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202107
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202108
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202109
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201901
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201902
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201903
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201904
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201905
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201906
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201907
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201908
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201909
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201910
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201911
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  201912
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202001
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
periodo =  202002
Inicio prediccion
Fin prediccion
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20

In [33]:
ncol(dataset)
colnames(dataset)

[1] 378

  [1] "numero_de_cliente"                  "foto_mes"
  [3] "internet"                           "cliente_edad"
  [5] "cliente_antiguedad"                 "mrentabilidad"
  [7] "mrentabilidad_annual"               "mcomisiones"
  [9] "mactivos_margen"                    "mpasivos_margen"
 [11] "cproductos"                         "mcuenta_corriente"
 [13] "mcaja_ahorro"                       "cdescubierto_preacordado"
 [15] "mcuentas_saldo"                     "ctarjeta_visa"
 [17] "ctarjeta_visa_transacciones"        "mtarjeta_visa_consumo"
 [19] "ctarjeta_master"                    "ctarjeta_master_transacciones"
 [21] "mtarjeta_master_consumo"            "cprestamos_personales"
 [23] "mprestamos_personales"              "cpayroll_trx"
 [25] "mpayroll"                           "mttarjeta_visa_debitos_automaticos"
 [27] "ccomisiones_mantenimiento"          "mcomisiones_mantenimiento"
 [29] "ccomisiones_otras"                  "mtransferencias_recibidas"
 [31] "ccallcenter_transacciones"          "thomebanking"
 [33] "chomebanking_transacciones"         "ctrx_quarter"
 [35] "Master_status"                      "Master_mfinanciacion_limite"
 [37] "Master_Fvencimiento"                "Master_msaldototal"
 [39] "Master_mlimitecompra"               "Master_fultimo_cierre"
 [41] "Master_fechaalta"                   "Master_mconsumototal"
 [43] "Master_cconsumos"                   "Master_mpagominimo"
 [45] "Visa_status"                        "Visa_mfinanciacion_limite"
 [47] "Visa_Fvencimiento"                  "Visa_msaldototal"
 [49] "Visa_mlimitecompra"                 "Visa_fultimo_cierre"
 [51] "Visa_fechaalta"                     "Visa_mconsumototal"
 [53] "Visa_cconsumos"                     "Visa_mpagominimo"
 [55] "clase_ternaria"                     "kmes"
 [57] "mpayroll_sobre_edad"                "entrenamiento"
 [59] "rf_001_006"                         "rf_001_008"
 [61] "rf_001_007"                         "rf_001_015"
 [63] "rf_001_001"                         "rf_001_012"
 [65] "rf_001_000"                         "rf_001_010"
 [67] "rf_001_011"                         "rf_001_003"
 [69] "rf_001_009"                         "rf_001_014"
 [71] "rf_001_005"                         "rf_001_002"
 [73] "rf_001_013"                         "rf_001_004"
 [75] "rf_002_009"                         "rf_002_014"
 [77] "rf_002_002"                         "rf_002_010"
 [79] "rf_002_006"                         "rf_002_003"
 [81] "rf_002_012"                         "rf_002_011"
 [83] "rf_002_008"                         "rf_002_013"
 [85] "rf_002_005"                         "rf_002_001"
 [87] "rf_002_015"                         "rf_002_004"
 [89] "rf_002_000"                         "rf_002_007"
 [91] "rf_003_005"                         "rf_003_007"
 [93] "rf_003_011"                         "rf_003_014"
 [95] "rf_003_006"                         "rf_003_001"
 [97] "rf_003_013"                         "rf_003_010"
 [99] "rf_003_012"                         "rf_003_004"
[101] "rf_003_003"                         "rf_003_009"
[103] "rf_003_002"                         "rf_003_015"
[105] "rf_003_008"                         "rf_003_000"
[107] "rf_004_011"                         "rf_004_014"
[109] "rf_004_012"                         "rf_004_013"
[111] "rf_004_009"                         "rf_004_000"
[113] "rf_004_001"                         "rf_004_002"
[115] "rf_004_004"                         "rf_004_007"
[117] "rf_004_015"                         "rf_004_006"
[119] "rf_004_010"                         "rf_004_005"
[121] "rf_004_008"                         "rf_004_003"
[123] "rf_005_009"                         "rf_005_008"
[125] "rf_005_010"                         "rf_005_011"
[127] "rf_005_001"                         "rf_005_004"
[129] "rf_005_013"                         "rf_005_003"
[131] "rf_005_002"                         "rf_005_006"
[133] "rf_005_007"                         "rf_005_000"
[135] "rf_005_015"                         "rf_005_005"
[137] "rf_005_012"                         "rf_005_014"
[139] "rf_006_004"                         "rf_006_012"
[141] "rf_006_014"                         "rf_006_002"
[143] "rf_006_010"                         "rf_006_001"
[145] "rf_006_015"                         "rf_006_003"
[147] "rf_006_011"                         "rf_006_008"
[149] "rf_006_013"                         "rf_006_005"
[151] "rf_006_000"                         "rf_006_007"
[153] "rf_006_009"                         "rf_006_006"
[155] "rf_007_004"                         "rf_007_014"
[157] "rf_007_013"                         "rf_007_007"
[159] "rf_007_002"                         "rf_007_012"
[161] "rf_007_015"                         "rf_007_011"
[163] "rf_007_003"                         "rf_007_006"
[165] "rf_007_009"                         "rf_007_001"
[167] "rf_007_000"                         "rf_007_010"
[169] "rf_007_005"                         "rf_007_008"
[171] "rf_008_011"                         "rf_008_010"
[173] "rf_008_012"                         "rf_008_014"
[175] "rf_008_002"                         "rf_008_003"
[177] "rf_008_000"                         "rf_008_001"
[179] "rf_008_009"                         "rf_008_013"
[181] "rf_008_004"                         "rf_008_006"
[183] "rf_008_008"                         "rf_008_005"
[185] "rf_008_007"                         "rf_008_015"
[187] "rf_009_004"                         "rf_009_003"
[189] "rf_009_015"                         "rf_009_002"
[191] "rf_009_005"                         "rf_009_013"
[193] "rf_009_001"                         "rf_009_009"
[195] "rf_009_014"                         "rf_009_011"
[197] "rf_009_010"                         "rf_009_000"
[199] "rf_009_012"                         "rf_009_007"
[201] "rf_009_008"                         "rf_009_006"
[203] "rf_010_006"                         "rf_010_014"
[205] "rf_010_001"                         "rf_010_008"
[207] "rf_010_002"                         "rf_010_011"
[209] "rf_010_003"                         "rf_010_009"
[211] "rf_010_013"                         "rf_010_007"
[213] "rf_010_010"                         "rf_010_000"
[215] "rf_010_012"                         "rf_010_004"
[217] "rf_010_005"                         "rf_010_015"
[219] "rf_011_005"                         "rf_011_003"
[221] "rf_011_013"                         "rf_011_004"
[223] "rf_011_002"                         "rf_011_001"
[225] "rf_011_008"                         "rf_011_006"
[227] "rf_011_015"                         "rf_011_014"
[229] "rf_011_011"                         "rf_011_012"
[231] "rf_011_009"                         "rf_011_000"
[233] "rf_011_007"                         "rf_011_010"
[235] "rf_012_001"                         "rf_012_002"
[237] "rf_012_007"                         "rf_012_014"
[239] "rf_012_009"                         "rf_012_013"
[241] "rf_012_006"                         "rf_012_003"
[243] "rf_012_011"                         "rf_012_010"
[245] "rf_012_005"                         "rf_012_000"
[247] "rf_012_012"                         "rf_012_008"
[249] "rf_012_004"                         "rf_012_015"
[251] "rf_013_006"                         "rf_013_012"
[253] "rf_013_008"                         "rf_013_007"
[255] "rf_013_001"                         "rf_013_002"
[257] "rf_013_000"                         "rf_013_015"
[259] "rf_013_010"                         "rf_013_005"
[261] "rf_013_009"                         "rf_013_014"
[263] "rf_013_004"                         "rf_013_011"
[265] "rf_013_003"                         "rf_013_013"
[267] "rf_014_014"                         "rf_014_013"
[269] "rf_014_004"                         "rf_014_005"
[271] "rf_014_002"                         "rf_014_006"
[273] "rf_014_001"                         "rf_014_015"
[275] "rf_014_010"                         "rf_014_007"
[277] "rf_014_003"                         "rf_014_009"
[279] "rf_014_000"                         "rf_014_011"
[281] "rf_014_008"                         "rf_014_012"
[283] "rf_015_001"                         "rf_015_011"
[285] "rf_015_006"                         "rf_015_002"
[287] "rf_015_004"                         "rf_015_007"
[289] "rf_015_003"                         "rf_015_005"
[291] "rf_015_008"                         "rf_015_013"
[293] "rf_015_014"                         "rf_015_009"
[295] "rf_015_012"                         "rf_015_010"
[297] "rf_015_015"                         "rf_015_000"
[299] "rf_016_007"                         "rf_016_010"
[301] "rf_016_013"                         "rf_016_002"
[303] "rf_016_011"                         "rf_016_008"
[305] "rf_016_009"                         "rf_016_012"
[307] "rf_016_003"                         "rf_016_001"
[309] "rf_016_015"                         "rf_016_000"
[311] "rf_016_014"                         "rf_016_004"
[313] "rf_016_006"                         "rf_016_005"
[315] "rf_017_005"                         "rf_017_013"
[317] "rf_017_002"                         "rf_017_007"
[319] "rf_017_003"                         "rf_017_008"
[321] "rf_017_010"                         "rf_017_000"
[323] "rf_017_009"                         "rf_017_006"
[325] "rf_017_015"                         "rf_017_014"
[327] "rf_017_001"                         "rf_017_011"
[329] "rf_017_004"                         "rf_017_012"
[331] "rf_018_006"                         "rf_018_015"
[333] "rf_018_014"                         "rf_018_013"
[335] "rf_018_002"                         "rf_018_001"
[337] "rf_018_000"                         "rf_018_008"
[339] "rf_018_010"                         "rf_018_009"
[341] "rf_018_003"                         "rf_018_004"
[343] "rf_018_007"                         "rf_018_011"
[345] "rf_018_005"                         "rf_018_012"
[347] "rf_019_013"                         "rf_019_012"
[349] "rf_019_014"                         "rf_019_008"
[351] "rf_019_009"                         "rf_019_010"
[353] "rf_019_003"                         "rf_019_000"
[355] "rf_019_002"                         "rf_019_001"
[357] "rf_019_015"                         "rf_019_007"
[359] "rf_019_011"                         "rf_019_005"
[361] "rf_019_006"                         "rf_019_004"
[363] "rf_020_007"                         "rf_020_006"
[365] "rf_020_010"                         "rf_020_008"
[367] "rf_020_003"                         "rf_020_012"
[369] "rf_020_002"                         "rf_020_000"
[371] "rf_020_014"                         "rf_020_005"
[373] "rf_020_001"                         "rf_020_013"
[375] "rf_020_015"                         "rf_020_009"
[377] "rf_020_004"                         "rf_020_011"

In [34]:
# No se implementa Feature Engineering a partir de Random Forest

#### 9.3.1.5  FEhist Feature Engineering historico

El Fature Engineering Histórico es la etapa que más aporta a la ganancia final, ya que enriquece cada registro del dataset con su historia.

Para cada campo del dataset original (*)
se crean lo siguientes campos de a partir de la historia
* lag1  lags de orden 1
* delta1  =  valor actual - lag1
* lag2  lags de orden 2
* delta2  = valor actual - lag2


(*) Excepto para los campos  <numero_de_cliente,  foto_mes,  clase_ternaria>

In [35]:
if( !require("Rcpp")) install.packages("Rcpp", repos = "http://cran.us.r-project.org")
require("Rcpp")

Loading required package: Rcpp

In [36]:
# se calculan para los 6 meses previos el minimo, maximo y
#  tendencia calculada con cuadrados minimos
# la formula de calculo de la tendencia puede verse en
#  https://stats.libretexts.org/Bookshelves/Introductory_Statistics/Book%3A_Introductory_Statistics_(Shafer_and_Zhang)/10%3A_Correlation_and_Regression/10.04%3A_The_Least_Squares_Regression_Line
# para la maxíma velocidad esta funcion esta escrita en lenguaje C,
# y no en la porqueria de R o Python

cppFunction("NumericVector fhistC(NumericVector pcolumna, IntegerVector pdesde )
{
  /* Aqui se cargan los valores para la regresion */
  double  x[100] ;
  double  y[100] ;

  int n = pcolumna.size();
  NumericVector out( 5*n );

  for(int i = 0; i < n; i++)
  {
    //lag
    if( pdesde[i]-1 < i )  out[ i + 4*n ]  =  pcolumna[i-1] ;
    else                   out[ i + 4*n ]  =  NA_REAL ;


    int  libre    = 0 ;
    int  xvalor   = 1 ;

    for( int j= pdesde[i]-1;  j<=i; j++ )
    {
       double a = pcolumna[j] ;

       if( !R_IsNA( a ) )
       {
          y[ libre ]= a ;
          x[ libre ]= xvalor ;
          libre++ ;
       }

       xvalor++ ;
    }

    /* Si hay al menos dos valores */
    if( libre > 1 )
    {
      double  xsum  = x[0] ;
      double  ysum  = y[0] ;
      double  xysum = xsum * ysum ;
      double  xxsum = xsum * xsum ;
      double  vmin  = y[0] ;
      double  vmax  = y[0] ;

      for( int h=1; h<libre; h++)
      {
        xsum  += x[h] ;
        ysum  += y[h] ;
        xysum += x[h]*y[h] ;
        xxsum += x[h]*x[h] ;

        if( y[h] < vmin )  vmin = y[h] ;
        if( y[h] > vmax )  vmax = y[h] ;
      }

      out[ i ]  =  (libre*xysum - xsum*ysum)/(libre*xxsum -xsum*xsum) ;
      out[ i + n ]    =  vmin ;
      out[ i + 2*n ]  =  vmax ;
      out[ i + 3*n ]  =  ysum / libre ;
    }
    else
    {
      out[ i       ]  =  NA_REAL ;
      out[ i + n   ]  =  NA_REAL ;
      out[ i + 2*n ]  =  NA_REAL ;
      out[ i + 3*n ]  =  NA_REAL ;
    }
  }

  return  out;
}")

In [37]:
# calcula la tendencia de las variables cols de los ultimos 6 meses
# la tendencia es la pendiente de la recta que ajusta por cuadrados minimos
# La funcionalidad de ratioavg es autoria de  Daiana Sparta,  UAustral  2021

TendenciaYmuchomas <- function(
    dataset, cols, ventana = 6, tendencia = TRUE,
    minimo = TRUE, maximo = TRUE, promedio = TRUE,
    ratioavg = FALSE, ratiomax = FALSE) {
  gc(verbose= FALSE)
  # Esta es la cantidad de meses que utilizo para la historia
  ventana_regresion <- ventana

  last <- nrow(dataset)

  # creo el vector_desde que indica cada ventana
  # de esta forma se acelera el procesamiento ya que lo hago una sola vez
  vector_ids <- dataset[ , numero_de_cliente ]

  vector_desde <- seq(
    -ventana_regresion + 2,
    nrow(dataset) - ventana_regresion + 1
  )

  vector_desde[1:ventana_regresion] <- 1

  for (i in 2:last) {
    if (vector_ids[i - 1] != vector_ids[i]) {
      vector_desde[i] <- i
    }
  }
  for (i in 2:last) {
    if (vector_desde[i] < vector_desde[i - 1]) {
      vector_desde[i] <- vector_desde[i - 1]
    }
  }

  for (campo in cols) {
    nueva_col <- fhistC(dataset[, get(campo)], vector_desde)

    if (tendencia) {
      dataset[, paste0(campo, "_tend", ventana) :=
        nueva_col[(0 * last + 1):(1 * last)]]
    }

    if (minimo) {
      dataset[, paste0(campo, "_min", ventana) :=
        nueva_col[(1 * last + 1):(2 * last)]]
    }

    if (maximo) {
      dataset[, paste0(campo, "_max", ventana) :=
        nueva_col[(2 * last + 1):(3 * last)]]
    }

    if (promedio) {
      dataset[, paste0(campo, "_avg", ventana) :=
        nueva_col[(3 * last + 1):(4 * last)]]
    }

    if (ratioavg) {
      dataset[, paste0(campo, "_ratioavg", ventana) :=
        get(campo) / nueva_col[(3 * last + 1):(4 * last)]]
    }

    if (ratiomax) {
      dataset[, paste0(campo, "_ratiomax", ventana) :=
        get(campo) / nueva_col[(2 * last + 1):(3 * last)]]
    }
  }
}

In [38]:
# parametros de Feature Engineering Historico de lags
PARAM$FEhist$usar_lags <- FALSE # TRUE: activa uso de lags; FALSE caso contrario.
PARAM$FEhist$lag_config <- list(
    lag1_activo = FALSE, # TRUE: activa lag1; FALSE caso contrario.
    lag2_activo = FALSE, # TRUE: activa lag2; FALSE caso contrario.
    lag3_activo = FALSE  # TRUE: activa lag3; FALSE caso contrario.
)

In [39]:
# parametros de Feature Engineering Historico de Tendencias
PARAM$FE_hist$Tendencias$run <- TRUE # esto activa las tendencias (usar_tendencias)
PARAM$FE_hist$Tendencias$ventana <- 6 # cantidad de meses: 6 o 12
PARAM$FE_hist$Tendencias$tendencia <- TRUE # ventana de tendencia segun la cantidad de meses
PARAM$FE_hist$Tendencias$minimo <- TRUE # ventana de minimo segun la cantidad de meses
PARAM$FE_hist$Tendencias$maximo <- TRUE # ventana de maximo segun la cantidad de meses
PARAM$FE_hist$Tendencias$promedio <- FALSE # ventana de promedio segun la cantidad de meses
PARAM$FE_hist$Tendencias$ratioavg <- FALSE # ventana del rationavg segun la cantidad de meses
PARAM$FE_hist$Tendencias$ratiomax <- FALSE # ventanta del ratiomax segun la cantidad de meses

In [40]:
# Feature Engineering Historico

setorder(dataset, numero_de_cliente, foto_mes)

# todo es lagueable, menos la primary key y la clase
cols_lagueables <- copy( setdiff(
    colnames(dataset),
    c("numero_de_cliente", "foto_mes", "clase_ternaria")
) )

if (isTRUE(PARAM$FEhist$usar_lags)) {
    
    # Lag 1
    if (isTRUE(PARAM$FEhist$lag_config$lag1_activo)) {
        dataset[,
            paste0(cols_lagueables, "_lag1") := shift(.SD, 1, NA, "lag"),
            by = numero_de_cliente,
            .SDcols = cols_lagueables
        ]
        for (vcol in cols_lagueables) {
            dataset[, paste0(vcol, "_delta1") := get(vcol) - get(paste0(vcol, "_lag1"))]
        }
    }
    
    # Lag 2
    if (isTRUE(PARAM$FEhist$lag_config$lag2_activo)) {
        dataset[,
            paste0(cols_lagueables, "_lag2") := shift(.SD, 2, NA, "lag"),
            by = numero_de_cliente,
            .SDcols = cols_lagueables
        ]
        for (vcol in cols_lagueables) {
            dataset[, paste0(vcol, "_delta2") := get(vcol) - get(paste0(vcol, "_lag2"))]
        }
    }
    
    # Lag 3
    if (isTRUE(PARAM$FEhist$lag_config$lag3_activo)) {
        dataset[,
            paste0(cols_lagueables, "_lag3") := shift(.SD, 3, NA, "lag"),
            by = numero_de_cliente,
            .SDcols = cols_lagueables
        ]
        for (vcol in cols_lagueables) {
            dataset[, paste0(vcol, "_delta3") := get(vcol) - get(paste0(vcol, "_lag3"))]
        }
    }
}

In [41]:
# Identificar columnas base ANTES de cualquier procesamiento
cols_base <- copy(setdiff(colnames(dataset), c("numero_de_cliente", "foto_mes", "clase_ternaria")))
columnas_control <- c("numero_de_cliente", "foto_mes", "clase_ternaria")
columnas_originales <- c(columnas_control, cols_base)

cat("=== CONFIGURACIÓN INICIAL ===\n")
cat("Total columnas originales:", length(columnas_originales), "\n")
cat("Columnas base para procesar:", length(cols_base), "\n")

# Crear dos copias independientes del dataset original
cat("\n=== CREANDO COPIAS INDEPENDIENTES ===\n")
dataset_copia_6 <- copy(dataset[, ..columnas_originales])
dataset_copia_12 <- copy(dataset[, ..columnas_originales])

cat("Copia para ventana 6 - Columnas:", ncol(dataset_copia_6), "\n")
cat("Copia para ventana 12 - Columnas:", ncol(dataset_copia_12), "\n")

# Procesar ventana 6 en su copia independiente
if (PARAM$FE_hist$Tendencias$run) {
  cat("\n=== PROCESANDO VENTANA 6 ===\n")
  setorder(dataset_copia_6, numero_de_cliente, foto_mes)
  
  TendenciaYmuchomas(
    dataset_copia_6,
    cols = cols_base,
    ventana = PARAM$FE_hist$Tendencias$ventana,
    tendencia = PARAM$FE_hist$Tendencias$tendencia,
    minimo = PARAM$FE_hist$Tendencias$minimo,
    maximo = PARAM$FE_hist$Tendencias$maximo,
    promedio = PARAM$FE_hist$Tendencias$promedio,
    ratioavg = PARAM$FE_hist$Tendencias$ratioavg,
    ratiomax = PARAM$FE_hist$Tendencias$ratiomax
  )
  
  cat("Ventana 6 completada - Columnas:", ncol(dataset_copia_6), "\n")
}

# Procesar ventana 12 en su copia independiente
if (PARAM$FE_hist$Tendencias$run) {
  cat("\n=== PROCESANDO VENTANA 12 ===\n")
  setorder(dataset_copia_12, numero_de_cliente, foto_mes)

  PARAM$FE_hist$Tendencias$ventana <- 12 # ACÁ INCORPORO LAS DE 12 meses
  TendenciaYmuchomas(
    dataset_copia_12,
    cols = cols_base,  # Exactamente las mismas columnas base
    ventana = PARAM$FE_hist$Tendencias$ventana,
    tendencia = PARAM$FE_hist$Tendencias$tendencia,
    minimo = PARAM$FE_hist$Tendencias$minimo,
    maximo = PARAM$FE_hist$Tendencias$maximo,
    promedio = PARAM$FE_hist$Tendencias$promedio,
    ratioavg = PARAM$FE_hist$Tendencias$ratioavg,
    ratiomax = PARAM$FE_hist$Tendencias$ratiomax
  )
  
  cat("Ventana 12 completada - Columnas:", ncol(dataset_copia_12), "\n")
}

# Combinar resultados en el dataset original
cat("\n=== COMBINANDO RESULTADOS ===\n")

# Extraer solo las columnas nuevas de cada copia
cols_nuevas_6 <- setdiff(colnames(dataset_copia_6), columnas_originales)
cols_nuevas_12 <- setdiff(colnames(dataset_copia_12), columnas_originales)

cat("Columnas nuevas de ventana 6:", length(cols_nuevas_6), "\n")
cat("Columnas nuevas de ventana 12:", length(cols_nuevas_12), "\n")

# Verificar que no hay conflictos de nombres (no debería haberlos)
conflictos <- intersect(cols_nuevas_6, cols_nuevas_12)
if(length(conflictos) > 0) {
  cat("WARNING: Conflictos de nombres:", length(conflictos), "\n")
  cat("Conflictos:", paste(head(conflictos, 5), collapse = ", "), "\n")
}

# Transferir columnas de ventana 6 al dataset original
if(length(cols_nuevas_6) > 0) {
  for(col in cols_nuevas_6) {
    dataset[, (col) := dataset_copia_6[[col]]]
  }
  cat("Columnas de ventana 6 transferidas al dataset original\n")
}

# Transferir columnas de ventana 12 al dataset original  
if(length(cols_nuevas_12) > 0) {
  for(col in cols_nuevas_12) {
    dataset[, (col) := dataset_copia_12[[col]]]
  }
  cat("Columnas de ventana 12 transferidas al dataset original\n")
}

# Limpiar memoria
rm(dataset_copia_6, dataset_copia_12)
gc()

=== CONFIGURACIÓN INICIAL ===
Total columnas originales: 378
Columnas base para procesar: 375

=== CREANDO COPIAS INDEPENDIENTES ===
Copia para ventana 6 - Columnas: 378
Copia para ventana 12 - Columnas: 378

=== PROCESANDO VENTANA 6 ===
Ventana 6 completada - Columnas: 1402

=== PROCESANDO VENTANA 12 ===
Ventana 12 completada - Columnas: 1402

=== COMBINANDO RESULTADOS ===
Columnas nuevas de ventana 6: 1024
Columnas nuevas de ventana 12: 1024

ERROR: Error: cannot allocate vector of size 7.4 Mb

Verificacion de los campos recien creados

In [44]:
ncol(dataset)
colnames(dataset)

[1] 2426

   [1] "numero_de_cliente"
   [2] "foto_mes"
   [3] "internet"
   [4] "cliente_edad"
   [5] "cliente_antiguedad"
   [6] "mrentabilidad"
   [7] "mrentabilidad_annual"
   [8] "mcomisiones"
   [9] "mactivos_margen"
  [10] "mpasivos_margen"
  [11] "cproductos"
  [12] "mcuenta_corriente"
  [13] "mcaja_ahorro"
  [14] "cdescubierto_preacordado"
  [15] "mcuentas_saldo"
  [16] "ctarjeta_visa"
  [17] "ctarjeta_visa_transacciones"
  [18] "mtarjeta_visa_consumo"
  [19] "ctarjeta_master"
  [20] "ctarjeta_master_transacciones"
  [21] "mtarjeta_master_consumo"
  [22] "cprestamos_personales"
  [23] "mprestamos_personales"
  [24] "cpayroll_trx"
  [25] "mpayroll"
  [26] "mttarjeta_visa_debitos_automaticos"
  [27] "ccomisiones_mantenimiento"
  [28] "mcomisiones_mantenimiento"
  [29] "ccomisiones_otras"
  [30] "mtransferencias_recibidas"
  [31] "ccallcenter_transacciones"
  [32] "thomebanking"
  [33] "chomebanking_transacciones"
  [34] "ctrx_quarter"
  [35] "Master_status"
  [36] "Master_mfinanciacion_limite"
  [37] "Master_Fvencimiento"
  [38] "Master_msaldototal"
  [39] "Master_mlimitecompra"
  [40] "Master_fultimo_cierre"
  [41] "Master_fechaalta"
  [42] "Master_mconsumototal"
  [43] "Master_cconsumos"
  [44] "Master_mpagominimo"
  [45] "Visa_status"
  [46] "Visa_mfinanciacion_limite"
  [47] "Visa_Fvencimiento"
  [48] "Visa_msaldototal"
  [49] "Visa_mlimitecompra"
  [50] "Visa_fultimo_cierre"
  [51] "Visa_fechaalta"
  [52] "Visa_mconsumototal"
  [53] "Visa_cconsumos"
  [54] "Visa_mpagominimo"
  [55] "clase_ternaria"
  [56] "kmes"
  [57] "mpayroll_sobre_edad"
  [58] "entrenamiento"
  [59] "rf_001_006"
  [60] "rf_001_008"
  [61] "rf_001_007"
  [62] "rf_001_015"
  [63] "rf_001_001"
  [64] "rf_001_012"
  [65] "rf_001_000"
  [66] "rf_001_010"
  [67] "rf_001_011"
  [68] "rf_001_003"
  [69] "rf_001_009"
  [70] "rf_001_014"
  [71] "rf_001_005"
  [72] "rf_001_002"
  [73] "rf_001_013"
  [74] "rf_001_004"
  [75] "rf_002_009"
  [76] "rf_002_014"
  [77] "rf_002_002"
  [78] "rf_002_010"
  [79] "rf_002_006"
  [80] "rf_002_003"
  [81] "rf_002_012"
  [82] "rf_002_011"
  [83] "rf_002_008"
  [84] "rf_002_013"
  [85] "rf_002_005"
  [86] "rf_002_001"
  [87] "rf_002_015"
  [88] "rf_002_004"
  [89] "rf_002_000"
  [90] "rf_002_007"
  [91] "rf_003_005"
  [92] "rf_003_007"
  [93] "rf_003_011"
  [94] "rf_003_014"
  [95] "rf_003_006"
  [96] "rf_003_001"
  [97] "rf_003_013"
  [98] "rf_003_010"
  [99] "rf_003_012"
 [100] "rf_003_004"
 [101] "rf_003_003"
 [102] "rf_003_009"
 [103] "rf_003_002"
 [104] "rf_003_015"
 [105] "rf_003_008"
 [106] "rf_003_000"
 [107] "rf_004_011"
 [108] "rf_004_014"
 [109] "rf_004_012"
 [110] "rf_004_013"
 [111] "rf_004_009"
 [112] "rf_004_000"
 [113] "rf_004_001"
 [114] "rf_004_002"
 [115] "rf_004_004"
 [116] "rf_004_007"
 [117] "rf_004_015"
 [118] "rf_004_006"
 [119] "rf_004_010"
 [120] "rf_004_005"
 [121] "rf_004_008"
 [122] "rf_004_003"
 [123] "rf_005_009"
 [124] "rf_005_008"
 [125] "rf_005_010"
 [126] "rf_005_011"
 [127] "rf_005_001"
 [128] "rf_005_004"
 [129] "rf_005_013"
 [130] "rf_005_003"
 [131] "rf_005_002"
 [132] "rf_005_006"
 [133] "rf_005_007"
 [134] "rf_005_000"
 [135] "rf_005_015"
 [136] "rf_005_005"
 [137] "rf_005_012"
 [138] "rf_005_014"
 [139] "rf_006_004"
 [140] "rf_006_012"
 [141] "rf_006_014"
 [142] "rf_006_002"
 [143] "rf_006_010"
 [144] "rf_006_001"
 [145] "rf_006_015"
 [146] "rf_006_003"
 [147] "rf_006_011"
 [148] "rf_006_008"
 [149] "rf_006_013"
 [150] "rf_006_005"
 [151] "rf_006_000"
 [152] "rf_006_007"
 [153] "rf_006_009"
 [154] "rf_006_006"
 [155] "rf_007_004"
 [156] "rf_007_014"
 [157] "rf_007_013"
 [158] "rf_007_007"
 [159] "rf_007_002"
 [160] "rf_007_012"
 [161] "rf_007_015"
 [162] "rf_007_011"
 [163] "rf_007_003"
 [164] "rf_007_006"
 [165] "rf_007_009"
 [166] "rf_007_001"
 [167] "rf_007_000"
 [168] "rf_007_010"
 [169] "rf_007_005"
 [170] "rf_007_008"
 [171] "rf_008_011"
 [172] "rf_008_010"
 [173] "rf_008_012"
 [174] "rf_008_014"
 [175] "rf_008_002"
 [176] "rf_008_003"
 [177] "rf_008_000"
 [178] "rf_008_001"
 [179] "rf_008_009"
 [180] "rf_008_013"
 [181] "rf_008_004"
 [182] "rf_008_006"
 [183] "rf_008_008"
 [184] "rf_008_005"
 [185] "rf_008_007"
 [186] "rf_008_015"
 [187] "rf_009_004"
 [188] "rf_009_003"
 [189] "rf_009_015"
 [190] "rf_009_002"
 [191] "rf_009_005"
 [192] "rf_009_013"
 [193] "rf_009_001"
 [194] "rf_009_009"
 [195] "rf_009_014"
 [196] "rf_009_011"
 [197] "rf_009_010"
 [198] "rf_009_000"
 [199] "rf_009_012"
 [200] "rf_009_007"
 [201] "rf_009_008"
 [202] "rf_009_006"
 [203] "rf_010_006"
 [204] "rf_010_014"
 [205] "rf_010_001"
 [206] "rf_010_008"
 [207] "rf_010_002"
 [208] "rf_010_011"
 [209] "rf_010_003"
 [210] "rf_010_009"
 [211] "rf_010_013"
 [212] "rf_010_007"
 [213] "rf_010_010"
 [214] "rf_010_000"
 [215] "rf_010_012"
 [216] "rf_010_004"
 [217] "rf_010_005"
 [218] "rf_010_015"
 [219] "rf_011_005"
 [220] "rf_011_003"
 [221] "rf_011_013"
 [222] "rf_011_004"
 [223] "rf_011_002"
 [224] "rf_011_001"
 [225] "rf_011_008"
 [226] "rf_011_006"
 [227] "rf_011_015"
 [228] "rf_011_014"
 [229] "rf_011_011"
 [230] "rf_011_012"
 [231] "rf_011_009"
 [232] "rf_011_000"
 [233] "rf_011_007"
 [234] "rf_011_010"
 [235] "rf_012_001"
 [236] "rf_012_002"
 [237] "rf_012_007"
 [238] "rf_012_014"
 [239] "rf_012_009"
 [240] "rf_012_013"
 [241] "rf_012_006"
 [242] "rf_012_003"
 [243] "rf_012_011"
 [244] "rf_012_010"
 [245] "rf_012_005"
 [246] "rf_012_000"
 [247] "rf_012_012"
 [248] "rf_012_008"
 [249] "rf_012_004"
 [250] "rf_012_015"
 [251] "rf_013_006"
 [252] "rf_013_012"
 [253] "rf_013_008"
 [254] "rf_013_007"
 [255] "rf_013_001"
 [256] "rf_013_002"
 [257] "rf_013_000"
 [258] "rf_013_015"
 [259] "rf_013_010"
 [260] "rf_013_005"
 [261] "rf_013_009"
 [262] "rf_013_014"
 [263] "rf_013_004"
 [264] "rf_013_011"
 [265] "rf_013_003"
 [266] "rf_013_013"
 [267] "rf_014_014"
 [268] "rf_014_013"
 [269] "rf_014_004"
 [270] "rf_014_005"
 [271] "rf_014_002"
 [272] "rf_014_006"
 [273] "rf_014_001"
 [274] "rf_014_015"
 [275] "rf_014_010"
 [276] "rf_014_007"
 [277] "rf_014_003"
 [278] "rf_014_009"
 [279] "rf_014_000"
 [280] "rf_014_011"
 [281] "rf_014_008"
 [282] "rf_014_012"
 [283] "rf_015_001"
 [284] "rf_015_011"
 [285] "rf_015_006"
 [286] "rf_015_002"
 [287] "rf_015_004"
 [288] "rf_015_007"
 [289] "rf_015_003"
 [290] "rf_015_005"
 [291] "rf_015_008"
 [292] "rf_015_013"
 [293] "rf_015_014"
 [294] "rf_015_009"
 [295] "rf_015_012"
 [296] "rf_015_010"
 [297] "rf_015_015"
 [298] "rf_015_000"
 [299] "rf_016_007"
 [300] "rf_016_010"
 [301] "rf_016_013"
 [302] "rf_016_002"
 [303] "rf_016_011"
 [304] "rf_016_008"
 [305] "rf_016_009"
 [306] "rf_016_012"
 [307] "rf_016_003"
 [308] "rf_016_001"
 [309] "rf_016_015"
 [310] "rf_016_000"
 [311] "rf_016_014"
 [312] "rf_016_004"
 [313] "rf_016_006"
 [314] "rf_016_005"
 [315] "rf_017_005"
 [316] "rf_017_013"
 [317] "rf_017_002"
 [318] "rf_017_007"
 [319] "rf_017_003"
 [320] "rf_017_008"
 [321] "rf_017_010"
 [322] "rf_017_000"
 [323] "rf_017_009"
 [324] "rf_017_006"
 [325] "rf_017_015"
 [326] "rf_017_014"
 [327] "rf_017_001"
 [328] "rf_017_011"
 [329] "rf_017_004"
 [330] "rf_017_012"
 [331] "rf_018_006"
 [332] "rf_018_015"
 [333] "rf_018_014"
 [334] "rf_018_013"
 [335] "rf_018_002"
 [336] "rf_018_001"
 [337] "rf_018_000"
 [338] "rf_018_008"
 [339] "rf_018_010"
 [340] "rf_018_009"
 [341] "rf_018_003"
 [342] "rf_018_004"
 [343] "rf_018_007"
 [344] "rf_018_011"
 [345] "rf_018_005"
 [346] "rf_018_012"
 [347] "rf_019_013"
 [348] "rf_019_012"
 [349] "rf_019_014"
 [350] "rf_019_008"
 [351] "rf_019_009"
 [352] "rf_019_010"
 [353] "rf_019_003"
 [354] "rf_019_000"
 [355] "rf_019_002"
 [356] "rf_019_001"
 [357] "rf_019_015"
 [358] "rf_019_007"
 [359] "rf_019_011"
 [360] "rf_019_005"
 [361] "rf_019_006"
 [362] "rf_019_004"
 [363] "rf_020_007"
 [364] "rf_020_006"
 [365] "rf_020_010"
 [366] "rf_020_008"
 [367] "rf_020_003"
 [368] "rf_020_012"
 [369] "rf_020_002"
 [370] "rf_020_000"
 [371] "rf_020_014"
 [372] "rf_020_005"
 [373] "rf_020_001"
 [374] "rf_020_013"
 [375] "rf_020_015"
 [376] "rf_020_009"
 [377] "rf_020_004"
 [378] "rf_020_011"
 [379] "internet_tend6"
 [380] "internet_min6"
 [381] "internet_max6"
 [382] "cliente_edad_tend6"
 [383] "cliente_edad_min6"
 [384] "cliente_edad_max6"
 [385] "cliente_antiguedad_tend6"
 [386] "cliente_antiguedad_min6"
 [387] "cliente_antiguedad_max6"
 [388] "mrentabilidad_tend6"
 [389] "mrentabilidad_min6"
 [390] "mrentabilidad_max6"
 [391] "mrentabilidad_annual_tend6"
 [392] "mrentabilidad_annual_min6"
 [393] "mrentabilidad_annual_max6"
 [394] "mcomisiones_tend6"
 [395] "mcomisiones_min6"
 [396] "mcomisiones_max6"
 [397] "mactivos_margen_tend6"
 [398] "mactivos_margen_min6"
 [399] "mactivos_margen_max6"
 [400] "mpasivos_margen_tend6"
 [401] "mpasivos_margen_min6"
 [402] "mpasivos_margen_max6"
 [403] "cproductos_tend6"
 [404] "cproductos_min6"
 [405] "cproductos_max6"
 [406] "mcuenta_corriente_tend6"
 [407] "mcuenta_corriente_min6"
 [408] "mcuenta_corriente_max6"
 [409] "mcaja_ahorro_tend6"
 [410] "mcaja_ahorro_min6"
 [411] "mcaja_ahorro_max6"
 [412] "cdescubierto_preacordado_tend6"
 [413] "cdescubierto_preacordado_min6"
 [414] "cdescubierto_preacordado_max6"
 [415] "mcuentas_saldo_tend6"
 [416] "mcuentas_saldo_min6"
 [417] "mcuentas_saldo_max6"
 [418] "ctarjeta_visa_tend6"
 [419] "ctarjeta_visa_min6"
 [420] "ctarjeta_visa_max6"
 [421] "ctarjeta_visa_transacciones_tend6"
 [422] "ctarjeta_visa_transacciones_min6"
 [423] "ctarjeta_visa_transacciones_max6"
 [424] "mtarjeta_visa_consumo_tend6"
 [425] "mtarjeta_visa_consumo_min6"
 [426] "mtarjeta_visa_consumo_max6"
 [427] "ctarjeta_master_tend6"
 [428] "ctarjeta_master_min6"
 [429] "ctarjeta_master_max6"
 [430] "ctarjeta_master_transacciones_tend6"
 [431] "ctarjeta_master_transacciones_min6"
 [432] "ctarjeta_master_transacciones_max6"
 [433] "mtarjeta_master_consumo_tend6"
 [434] "mtarjeta_master_consumo_min6"
 [435] "mtarjeta_master_consumo_max6"
 [436] "cprestamos_personales_tend6"
 [437] "cprestamos_personales_min6"
 [438] "cprestamos_personales_max6"
 [439] "mprestamos_personales_tend6"
 [440] "mprestamos_personales_min6"
 [441] "mprestamos_personales_max6"
 [442] "cpayroll_trx_tend6"
 [443] "cpayroll_trx_min6"
 [444] "cpayroll_trx_max6"
 [445] "mpayroll_tend6"
 [446] "mpayroll_min6"
 [447] "mpayroll_max6"
 [448] "mttarjeta_visa_debitos_automaticos_tend6"
 [449] "mttarjeta_visa_debitos_automaticos_min6"
 [450] "mttarjeta_visa_debitos_automaticos_max6"
 [451] "ccomisiones_mantenimiento_tend6"
 [452] "ccomisiones_mantenimiento_min6"
 [453] "ccomisiones_mantenimiento_max6"
 [454] "mcomisiones_mantenimiento_tend6"
 [455] "mcomisiones_mantenimiento_min6"
 [456] "mcomisiones_mantenimiento_max6"
 [457] "ccomisiones_otras_tend6"
 [458] "ccomisiones_otras_min6"
 [459] "ccomisiones_otras_max6"
 [460] "mtransferencias_recibidas_tend6"
 [461] "mtransferencias_recibidas_min6"
 [462] "mtransferencias_recibidas_max6"
 [463] "ccallcenter_transacciones_tend6"
 [464] "ccallcenter_transacciones_min6"
 [465] "ccallcenter_transacciones_max6"
 [466] "thomebanking_tend6"
 [467] "thomebanking_min6"
 [468] "thomebanking_max6"
 [469] "chomebanking_transacciones_tend6"
 [470] "chomebanking_transacciones_min6"
 [471] "chomebanking_transacciones_max6"
 [472] "ctrx_quarter_tend6"
 [473] "ctrx_quarter_min6"
 [474] "ctrx_quarter_max6"
 [475] "Master_status_tend6"
 [476] "Master_status_min6"
 [477] "Master_status_max6"
 [478] "Master_mfinanciacion_limite_tend6"
 [479] "Master_mfinanciacion_limite_min6"
 [480] "Master_mfinanciacion_limite_max6"
 [481] "Master_Fvencimiento_tend6"
 [482] "Master_Fvencimiento_min6"
 [483] "Master_Fvencimiento_max6"
 [484] "Master_msaldototal_tend6"
 [485] "Master_msaldototal_min6"
 [486] "Master_msaldototal_max6"
 [487] "Master_mlimitecompra_tend6"
 [488] "Master_mlimitecompra_min6"
 [489] "Master_mlimitecompra_max6"
 [490] "Master_fultimo_cierre_tend6"
 [491] "Master_fultimo_cierre_min6"
 [492] "Master_fultimo_cierre_max6"
 [493] "Master_fechaalta_tend6"
 [494] "Master_fechaalta_min6"
 [495] "Master_fechaalta_max6"
 [496] "Master_mconsumototal_tend6"
 [497] "Master_mconsumototal_min6"
 [498] "Master_mconsumototal_max6"
 [499] "Master_cconsumos_tend6"
 [500] "Master_cconsumos_min6"
 [501] "Master_cconsumos_max6"
 [502] "Master_mpagominimo_tend6"
 [503] "Master_mpagominimo_min6"
 [504] "Master_mpagominimo_max6"
 [505] "Visa_status_tend6"
 [506] "Visa_status_min6"
 [507] "Visa_status_max6"
 [508] "Visa_mfinanciacion_limite_tend6"
 [509] "Visa_mfinanciacion_limite_min6"
 [510] "Visa_mfinanciacion_limite_max6"
 [511] "Visa_Fvencimiento_tend6"
 [512] "Visa_Fvencimiento_min6"
 [513] "Visa_Fvencimiento_max6"
 [514] "Visa_msaldototal_tend6"
 [515] "Visa_msaldototal_min6"
 [516] "Visa_msaldototal_max6"
 [517] "Visa_mlimitecompra_tend6"
 [518] "Visa_mlimitecompra_min6"
 [519] "Visa_mlimitecompra_max6"
 [520] "Visa_fultimo_cierre_tend6"
 [521] "Visa_fultimo_cierre_min6"
 [522] "Visa_fultimo_cierre_max6"
 [523] "Visa_fechaalta_tend6"
 [524] "Visa_fechaalta_min6"
 [525] "Visa_fechaalta_max6"
 [526] "Visa_mconsumototal_tend6"
 [527] "Visa_mconsumototal_min6"
 [528] "Visa_mconsumototal_max6"
 [529] "Visa_cconsumos_tend6"
 [530] "Visa_cconsumos_min6"
 [531] "Visa_cconsumos_max6"
 [532] "Visa_mpagominimo_tend6"
 [533] "Visa_mpagominimo_min6"
 [534] "Visa_mpagominimo_max6"
 [535] "kmes_tend6"
 [536] "kmes_min6"
 [537] "kmes_max6"
 [538] "mpayroll_sobre_edad_tend6"
 [539] "mpayroll_sobre_edad_min6"
 [540] "mpayroll_sobre_edad_max6"
 [541] "entrenamiento_tend6"
 [542] "entrenamiento_min6"
 [543] "entrenamiento_max6"
 [544] "rf_001_006_tend6"
 [545] "rf_001_006_min6"
 [546] "rf_001_006_max6"
 [547] "rf_001_008_tend6"
 [548] "rf_001_008_min6"
 [549] "rf_001_008_max6"
 [550] "rf_001_007_tend6"
 [551] "rf_001_007_min6"
 [552] "rf_001_007_max6"
 [553] "rf_001_015_tend6"
 [554] "rf_001_015_min6"
 [555] "rf_001_015_max6"
 [556] "rf_001_001_tend6"
 [557] "rf_001_001_min6"
 [558] "rf_001_001_max6"
 [559] "rf_001_012_tend6"
 [560] "rf_001_012_min6"
 [561] "rf_001_012_max6"
 [562] "rf_001_000_tend6"
 [563] "rf_001_000_min6"
 [564] "rf_001_000_max6"
 [565] "rf_001_010_tend6"
 [566] "rf_001_010_min6"
 [567] "rf_001_010_max6"
 [568] "rf_001_011_tend6"
 [569] "rf_001_011_min6"
 [570] "rf_001_011_max6"
 [571] "rf_001_003_tend6"
 [572] "rf_001_003_min6"
 [573] "rf_001_003_max6"
 [574] "rf_001_009_tend6"
 [575] "rf_001_009_min6"
 [576] "rf_001_009_max6"
 [577] "rf_001_014_tend6"
 [578] "rf_001_014_min6"
 [579] "rf_001_014_max6"
 [580] "rf_001_005_tend6"
 [581] "rf_001_005_min6"
 [582] "rf_001_005_max6"
 [583] "rf_001_002_tend6"
 [584] "rf_001_002_min6"
 [585] "rf_001_002_max6"
 [586] "rf_001_013_tend6"
 [587] "rf_001_013_min6"
 [588] "rf_001_013_max6"
 [589] "rf_001_004_tend6"
 [590] "rf_001_004_min6"
 [591] "rf_001_004_max6"
 [592] "rf_002_009_tend6"
 [593] "rf_002_009_min6"
 [594] "rf_002_009_max6"
 [595] "rf_002_014_tend6"
 [596] "rf_002_014_min6"
 [597] "rf_002_014_max6"
 [598] "rf_002_002_tend6"
 [599] "rf_002_002_min6"
 [600] "rf_002_002_max6"
 [601] "rf_002_010_tend6"
 [602] "rf_002_010_min6"
 [603] "rf_002_010_max6"
 [604] "rf_002_006_tend6"
 [605] "rf_002_006_min6"
 [606] "rf_002_006_max6"
 [607] "rf_002_003_tend6"
 [608] "rf_002_003_min6"
 [609] "rf_002_003_max6"
 [610] "rf_002_012_tend6"
 [611] "rf_002_012_min6"
 [612] "rf_002_012_max6"
 [613] "rf_002_011_tend6"
 [614] "rf_002_011_min6"
 [615] "rf_002_011_max6"
 [616] "rf_002_008_tend6"
 [617] "rf_002_008_min6"
 [618] "rf_002_008_max6"
 [619] "rf_002_013_tend6"
 [620] "rf_002_013_min6"
 [621] "rf_002_013_max6"
 [622] "rf_002_005_tend6"
 [623] "rf_002_005_min6"
 [624] "rf_002_005_max6"
 [625] "rf_002_001_tend6"
 [626] "rf_002_001_min6"
 [627] "rf_002_001_max6"
 [628] "rf_002_015_tend6"
 [629] "rf_002_015_min6"
 [630] "rf_002_015_max6"
 [631] "rf_002_004_tend6"
 [632] "rf_002_004_min6"
 [633] "rf_002_004_max6"
 [634] "rf_002_000_tend6"
 [635] "rf_002_000_min6"
 [636] "rf_002_000_max6"
 [637] "rf_002_007_tend6"
 [638] "rf_002_007_min6"
 [639] "rf_002_007_max6"
 [640] "rf_003_005_tend6"
 [641] "rf_003_005_min6"
 [642] "rf_003_005_max6"
 [643] "rf_003_007_tend6"
 [644] "rf_003_007_min6"
 [645] "rf_003_007_max6"
 [646] "rf_003_011_tend6"
 [647] "rf_003_011_min6"
 [648] "rf_003_011_max6"
 [649] "rf_003_014_tend6"
 [650] "rf_003_014_min6"
 [651] "rf_003_014_max6"
 [652] "rf_003_006_tend6"
 [653] "rf_003_006_min6"
 [654] "rf_003_006_max6"
 [655] "rf_003_001_tend6"
 [656] "rf_003_001_min6"
 [657] "rf_003_001_max6"
 [658] "rf_003_013_tend6"
 [659] "rf_003_013_min6"
 [660] "rf_003_013_max6"
 [661] "rf_003_010_tend6"
 [662] "rf_003_010_min6"
 [663] "rf_003_010_max6"
 [664] "rf_003_012_tend6"
 [665] "rf_003_012_min6"
 [666] "rf_003_012_max6"
 [667] "rf_003_004_tend6"
 [668] "rf_003_004_min6"
 [669] "rf_003_004_max6"
 [670] "rf_003_003_tend6"
 [671] "rf_003_003_min6"
 [672] "rf_003_003_max6"
 [673] "rf_003_009_tend6"
 [674] "rf_003_009_min6"
 [675] "rf_003_009_max6"
 [676] "rf_003_002_tend6"
 [677] "rf_003_002_min6"
 [678] "rf_003_002_max6"
 [679] "rf_003_015_tend6"
 [680] "rf_003_015_min6"
 [681] "rf_003_015_max6"
 [682] "rf_003_008_tend6"
 [683] "rf_003_008_min6"
 [684] "rf_003_008_max6"
 [685] "rf_003_000_tend6"
 [686] "rf_003_000_min6"
 [687] "rf_003_000_max6"
 [688] "rf_004_011_tend6"
 [689] "rf_004_011_min6"
 [690] "rf_004_011_max6"
 [691] "rf_004_014_tend6"
 [692] "rf_004_014_min6"
 [693] "rf_004_014_max6"
 [694] "rf_004_012_tend6"
 [695] "rf_004_012_min6"
 [696] "rf_004_012_max6"
 [697] "rf_004_013_tend6"
 [698] "rf_004_013_min6"
 [699] "rf_004_013_max6"
 [700] "rf_004_009_tend6"
 [701] "rf_004_009_min6"
 [702] "rf_004_009_max6"
 [703] "rf_004_000_tend6"
 [704] "rf_004_000_min6"
 [705] "rf_004_000_max6"
 [706] "rf_004_001_tend6"
 [707] "rf_004_001_min6"
 [708] "rf_004_001_max6"
 [709] "rf_004_002_tend6"
 [710] "rf_004_002_min6"
 [711] "rf_004_002_max6"
 [712] "rf_004_004_tend6"
 [713] "rf_004_004_min6"
 [714] "rf_004_004_max6"
 [715] "rf_004_007_tend6"
 [716] "rf_004_007_min6"
 [717] "rf_004_007_max6"
 [718] "rf_004_015_tend6"
 [719] "rf_004_015_min6"
 [720] "rf_004_015_max6"
 [721] "rf_004_006_tend6"
 [722] "rf_004_006_min6"
 [723] "rf_004_006_max6"
 [724] "rf_004_010_tend6"
 [725] "rf_004_010_min6"
 [726] "rf_004_010_max6"
 [727] "rf_004_005_tend6"
 [728] "rf_004_005_min6"
 [729] "rf_004_005_max6"
 [730] "rf_004_008_tend6"
 [731] "rf_004_008_min6"
 [732] "rf_004_008_max6"
 [733] "rf_004_003_tend6"
 [734] "rf_004_003_min6"
 [735] "rf_004_003_max6"
 [736] "rf_005_009_tend6"
 [737] "rf_005_009_min6"
 [738] "rf_005_009_max6"
 [739] "rf_005_008_tend6"
 [740] "rf_005_008_min6"
 [741] "rf_005_008_max6"
 [742] "rf_005_010_tend6"
 [743] "rf_005_010_min6"
 [744] "rf_005_010_max6"
 [745] "rf_005_011_tend6"
 [746] "rf_005_011_min6"
 [747] "rf_005_011_max6"
 [748] "rf_005_001_tend6"
 [749] "rf_005_001_min6"
 [750] "rf_005_001_max6"
 [751] "rf_005_004_tend6"
 [752] "rf_005_004_min6"
 [753] "rf_005_004_max6"
 [754] "rf_005_013_tend6"
 [755] "rf_005_013_min6"
 [756] "rf_005_013_max6"
 [757] "rf_005_003_tend6"
 [758] "rf_005_003_min6"
 [759] "rf_005_003_max6"
 [760] "rf_005_002_tend6"
 [761] "rf_005_002_min6"
 [762] "rf_005_002_max6"
 [763] "rf_005_006_tend6"
 [764] "rf_005_006_min6"
 [765] "rf_005_006_max6"
 [766] "rf_005_007_tend6"
 [767] "rf_005_007_min6"
 [768] "rf_005_007_max6"
 [769] "rf_005_000_tend6"
 [770] "rf_005_000_min6"
 [771] "rf_005_000_max6"
 [772] "rf_005_015_tend6"
 [773] "rf_005_015_min6"
 [774] "rf_005_015_max6"
 [775] "rf_005_005_tend6"
 [776] "rf_005_005_min6"
 [777] "rf_005_005_max6"
 [778] "rf_005_012_tend6"
 [779] "rf_005_012_min6"
 [780] "rf_005_012_max6"
 [781] "rf_005_014_tend6"
 [782] "rf_005_014_min6"
 [783] "rf_005_014_max6"
 [784] "rf_006_004_tend6"
 [785] "rf_006_004_min6"
 [786] "rf_006_004_max6"
 [787] "rf_006_012_tend6"
 [788] "rf_006_012_min6"
 [789] "rf_006_012_max6"
 [790] "rf_006_014_tend6"
 [791] "rf_006_014_min6"
 [792] "rf_006_014_max6"
 [793] "rf_006_002_tend6"
 [794] "rf_006_002_min6"
 [795] "rf_006_002_max6"
 [796] "rf_006_010_tend6"
 [797] "rf_006_010_min6"
 [798] "rf_006_010_max6"
 [799] "rf_006_001_tend6"
 [800] "rf_006_001_min6"
 [801] "rf_006_001_max6"
 [802] "rf_006_015_tend6"

#### 9.3.1.6  FEhist Reduccion dimensionalidad con canaritos

Esta etapa solo se mostrará a la *modalidad Anlista Sr* por algun canal secreto de forma de no confundir a los *Analista Jr*  nni distraer con detalles operativos a la estratégica *Modalidad Gerencial*

In [45]:
# No se implementa la reduccion de la dimensionalidad con canaritos

### 9.3.2 Modelado

#### 9.3.2.1 Training Strategy

Se hace una estrategia de entrenamiento muy sencilla, tomando todos los meses posibles, SIN eliminar nada x pandemia ni por ningun otro motivo

* future = 202109  obviamente completo

* final_train =  [ 201901, 202107 ]  SIN undersampling

* training
   * testing = NO HAY
   * validation =  202107   completo, sin undersampling
   * training = [ 201901, 202105 ]  donde se consideran el 100% de los CONTINUA

In [46]:
PARAM$trainingstrategy$validate <- c(202105)

PARAM$trainingstrategy$training <- c(
  201901, 201902, 201903, 201904, 201905, 201906,
  201907, 201908, 201909, 201910, 201911, 201912,
  202001, 202002, 202003, 202004, 202005, 202006,
  202007, 202008, 202009, 202010, 202011, 202012,
  202101, 202102, 202103
) # Corregido para el grupo B

PARAM$trainingstrategy$training_pct <- 1.0


PARAM$trainingstrategy$positivos <- c( "BAJA+1", "BAJA+2")

In [47]:
# seteo la clase01   1={BAJA+1, BAJA+2}   0={CONTINUA}
dataset[, clase01 := ifelse( clase_ternaria %in% PARAM$trainingstrategy$positivos, 1, 0 )]

In [48]:
# los campos en los que se entrena
campos_buenos <- copy( setdiff(
    colnames(dataset), c("clase_ternaria","clase01","azar"))
)

In [ ]:
# preparo para que se puede hacer undersampling de los CONTINUA
#  solamente por un tema de VELOCIDAD
set.seed(PARAM$semilla_primigenia, kind = "L'Ecuyer-CMRG")
dataset[, azar:=runif(nrow(dataset))]

# undersampling de los CONTINUA
dataset[, fold_train :=  foto_mes %in%  PARAM$trainingstrategy$training &
    (clase_ternaria %in% c("BAJA+1", "BAJA+2") |
     azar < PARAM$trainingstrategy$training_pct ) ]


if( !require("lightgbm")) install.packages("lightgbm")
require("lightgbm")

dtrain <- lgb.Dataset(
  data= data.matrix(dataset[fold_train == TRUE, campos_buenos, with = FALSE]),
  label= dataset[fold_train == TRUE, clase01],
  free_raw_data= TRUE
)

In [49]:
# datos de validation
dvalidate <- lgb.Dataset(
  data= data.matrix(dataset[foto_mes %in% PARAM$trainingstrategy$validate, campos_buenos, with = FALSE]),
  label= dataset[foto_mes %in% PARAM$trainingstrategy$validate, clase01],
  free_raw_data= TRUE
)

nrow(dvalidate)

[1] 32900

####  9.3.2.2. Hyperparameter Tuning

* Clase binaria que se optimiza :  positivos = [ BAJA+1, BAJA+2 ]

* Metrica que se optimiza **AUC** Area Under Curve de la  ROC Curve

es muy importante notar que intencionalmente  **NO** se está optimizando la funcion de ganancia del problema

* Cantidad de iteraciones inteligentes de la Optimizacion Bayesiana = **10**

* Parametros no default, fijos de LightGBM que no se optimizan
  * max_bin = 31 , Alienigenas Ancestrales contruyeron las pirámides y dejaron a la humanidad en un jeroglifico  *max_bin=31*
  * feature_fraction = 0.5  para poner algo que generalmente no falla
  * learning_rate = 0.03  para que aprenda lento

* Parametros que se optimizan en la Bayesian Optimization
  * num_leaves  [8, 256]
  * min_data_in_leaf  [8, 8192]

In [50]:
# paquetes necesarios para la Bayesian Optimization
if(!require("DiceKriging")) install.packages("DiceKriging")
require("DiceKriging")

if(!require("mlrMBO")) install.packages("mlrMBO")
require("mlrMBO")

Loading required package: DiceKriging

Loading required package: mlrMBO

Loading required package: mlr

Loading required package: ParamHelpers


Attaching package: 'ParamHelpers'


The following object is masked from 'package:R.utils':

    isVector



Attaching package: 'mlr'


The following objects are masked from 'package:R.utils':

    resample, setThreshold


Loading required package: smoof

Loading required package: checkmate


Attaching package: 'checkmate'


The following object is masked from 'package:DiceKriging':

    checkNames


The following object is masked from 'package:R.utils':

    asInt



Attaching package: 'smoof'


The following objects are masked from 'package:R.oo':

    getDescription, getName

Definición de la Bayesian Optimization
<br> Si se desea optimizar un hiperparámetro que esta como fijo, debe QUITARSE de param_fijos y agregarse a PARAM$hipeparametertuning$hs

In [51]:
# un Analista Jr  debe poder animarse a hacer 100 iteraciones
PARAM$hipeparametertuning$num_interations <- 20

# parametros fijos del LightGBM
PARAM$lgbm$param_fijos <- list(
  objective= "binary",
  metric= "auc",
  first_metric_only= TRUE,
  boost_from_average= TRUE,
  feature_pre_filter= FALSE,
  verbosity= -100,
  force_row_wise= TRUE, # para evitar warning
  seed= PARAM$semilla_primigenia,
  max_bin= 31,

  num_iterations= 9999,  # valor grande, lo limita early_stopping_rounds
  early_stopping_rounds= 400
)

PARAM$hipeparametertuning$hs <- makeParamSet(
  makeIntegerParam("num_leaves", lower= 2L, upper= 256L),
  makeIntegerParam("min_data_in_leaf", lower= 2L, upper= 8192L),
  makeNumericParam("feature_fraction", lower= 0.1, upper= 0.9),
  makeNumericParam("learning_rate", lower= 0.01, upper= 0.5)
)

Función "señora caja negra"  que es llamada para verificar la realidad por la Bayesian Optimization

In [52]:
# En  x llegan los parmaetros de la bayesiana
#  devuelve la AUC en validate del modelo entrenado
#  en el parametro x llegan los hiperparámetros que se estan optimizando

EstimarGanancia_AUC_lightgbm <- function(x) {

  # x pisa (o agrega) a param_fijos
  param_completo <- modifyList(PARAM$lgbm$param_fijos, x)

  # entreno LightGBM
  modelo_train <- lgb.train(
    data= dtrain,
    valids= list(valid = dvalidate),
    eval= "auc",
    param= param_completo,
    verbose= -100
  )

  # recupero la AUC en validation
  AUC <- modelo_train$record_evals$valid$auc$eval[[modelo_train$best_iter]]

  # esta es la forma de devolver un parametro extra
  attr(AUC, "extras") <- list("num_iterations"= modelo_train$best_iter)

  # hago espacio en la memoria
  rm(modelo_train)
  gc(full= TRUE, verbose= FALSE)

  message(format(Sys.time(), "%a %b %d %X %Y"), " AUC ", AUC)

  return(AUC)
}

seteo de la Bayesian Optimization (complejo)
<br> copiado y pegado de la documentación de la librería

In [54]:
configureMlr(show.learner.output = FALSE)

# configuro la busqueda bayesiana,  los hiperparametros que se van a optimizar
# por favor, no desesperarse por lo complejo
obj.fun <- makeSingleObjectiveFunction(
    fn= EstimarGanancia_AUC_lightgbm, # la funcion que voy a maximizar
    minimize= FALSE, # estoy Maximizando AUC
    noisy= FALSE,
    par.set= PARAM$hipeparametertuning$hs,
    has.simple.signature= FALSE # paso los parametros en una lista
)

# cada 600 segundos guardo el resultado intermedio
ctrl <- makeMBOControl(
    save.on.disk.at.time= 600,
    save.file.path= "HT.RDATA"
)

# indico la cantidad de iteraciones que va a tener la Bayesian Optimization
ctrl <- setMBOControlTermination(
    ctrl,
    iters= PARAM$hipeparametertuning$num_interations  # cantidad de iteraciones inteligentes
)

# defino el método estandar para la creacion de los puntos iniciales
#   los "No Inteligentes"
ctrl <- setMBOControlInfill(ctrl, crit = makeMBOInfillCritEI())

# mas configuraciones
surr.km <- makeLearner(
    "regr.km",
    predict.type= "se",
    covtype= "matern3_2",
    control= list(trace = TRUE)
)

Corrida de la Bayesian Optimization,  aqui se hace el trabajo pesado
<br> por favor no se asuste con los warnings que pudieran aparecer

Si corrío a medias y llegó a las iteraciones inteligentes, en el archivo binario HT.RDATA quedó lo ya procesado y es utilizado para retomar la corrida desde lo último que llegó a grabar.

In [55]:
# inicio la optimizacion bayesiana

if (!file.exists("HT.RDATA")) {
  bayesiana_salida <- mbo(obj.fun, learner= surr.km, control= ctrl)
} else {
  bayesiana_salida <- mboContinue("HT.RDATA") # retomo en caso que ya exista
}

Computing y column(s) for design. Not provided.

Tue Aug 12 2:15:24 PM 2025 AUC 0.918536855674742

Tue Aug 12 2:15:59 PM 2025 AUC 0.907675564380483

Tue Aug 12 2:17:08 PM 2025 AUC 0.921054990866608

Tue Aug 12 2:17:47 PM 2025 AUC 0.924018631509134

Tue Aug 12 2:18:46 PM 2025 AUC 0.920660509479948

Tue Aug 12 2:20:23 PM 2025 AUC 0.926191611406162

Tue Aug 12 2:21:07 PM 2025 AUC 0.909281761163912

Tue Aug 12 2:22:03 PM 2025 AUC 0.917714357950874

Tue Aug 12 2:23:26 PM 2025 AUC 0.92534007835802

Tue Aug 12 2:23:51 PM 2025 AUC 0.927223044606748

Tue Aug 12 2:25:58 PM 2025 AUC 0.904316890510339

Tue Aug 12 2:26:41 PM 2025 AUC 0.920432599164122

Tue Aug 12 2:28:16 PM 2025 AUC 0.926462353070222

Tue Aug 12 2:28:35 PM 2025 AUC 0.912695364434071

Tue Aug 12 2:29:32 PM 2025 AUC 0.886344321930092

Tue Aug 12 2:30:26 PM 2025 AUC 0.923639898814442

[mbo] 0: num_leaves=113; min_data_in_leaf=4971; feature_fraction=0.375; learning_rate=0.285 : y = 0.919 : 67.9 secs : initdesign

[mbo] 0: num_leaves=64; min_data_in_leaf=1304; feature_fraction=0.163; learning_rate=0.29 : y = 0.908 : 35.2 secs : initdesign

[mbo] 0: num_leaves=147; min_data_in_leaf=4435; feature_fraction=0.429; learning_rate=0.238 : y = 0.921 : 68.7 secs : initdesign

[mbo] 0: num_leaves=82; min_data_in_leaf=3025; feature_fraction=0.724; learning_rate=0.206 : y = 0.924 : 38.9 secs : initdesign

[mbo] 0: num_leaves=220; min_data_in_leaf=7807; feature_fraction=0.538; learning_rate=0.383 : y = 0.921 : 59.0 secs : initdesign

[mbo] 0: num_leaves=208; min_data_in_leaf=2114; feature_fraction=0.253; learning_rate=0.0506 : y = 0.926 : 96.8 secs : initdesign

[mbo] 0: num_leaves=74; min_data_in_leaf=1561; feature_fraction=0.336; learning_rate=0.362 : y = 0.909 : 44.4 secs : initdesign

[mbo] 0: num_leaves=142; min_data_in_leaf=6208; feature_fraction=0.623; learning_rate=0.322 : y = 0.918 : 56.2 secs : initdesign

[mbo] 0: num_leaves=230; min_data_in_leaf=6942; feature_fraction=0.49; learning_rate=0.0736 : y = 0.925 : 82.8 secs : initdesign

[mbo] 0: num_leaves=6; min_data_in_leaf=6003; feature_fraction=0.847; learning_rate=0.139 : y = 0.927 : 24.7 secs : initdesign

[mbo] 0: num_leaves=248; min_data_in_leaf=3206; feature_fraction=0.147; learning_rate=0.445 : y = 0.904 : 127.4 secs : initdesign

[mbo] 0: num_leaves=49; min_data_in_leaf=149; feature_fraction=0.584; learning_rate=0.126 : y = 0.92 : 43.0 secs : initdesign

[mbo] 0: num_leaves=181; min_data_in_leaf=3663; feature_fraction=0.858; learning_rate=0.0404 : y = 0.926 : 94.3 secs : initdesign

[mbo] 0: num_leaves=28; min_data_in_leaf=7328; feature_fraction=0.663; learning_rate=0.481 : y = 0.913 : 19.9 secs : initdesign

[mbo] 0: num_leaves=166; min_data_in_leaf=621; feature_fraction=0.788; learning_rate=0.418 : y = 0.886 : 56.6 secs : initdesign

[mbo] 0: num_leaves=106; min_data_in_leaf=5258; feature_fraction=0.237; learning_rate=0.175 : y = 0.924 : 53.5 secs : initdesign

Saved the current state after iteration 1 in the file HT.RDATA.

Tue Aug 12 2:31:19 PM 2025 AUC 0.928842910066224

[mbo] 1: num_leaves=29; min_data_in_leaf=3554; feature_fraction=0.55; learning_rate=0.0747 : y = 0.929 : 53.0 secs : infill_ei

Tue Aug 12 2:32:15 PM 2025 AUC 0.92612055127044

[mbo] 2: num_leaves=96; min_data_in_leaf=4085; feature_fraction=0.65; learning_rate=0.113 : y = 0.926 : 56.3 secs : infill_ei

Tue Aug 12 2:41:16 PM 2025 AUC 0.917414198918799

[mbo] 3: num_leaves=2; min_data_in_leaf=2342; feature_fraction=0.556; learning_rate=0.0101 : y = 0.917 : 539.9 secs : infill_ei

Saved the current state after iteration 4 in the file HT.RDATA.

Tue Aug 12 2:42:13 PM 2025 AUC 0.929281071787207

[mbo] 4: num_leaves=19; min_data_in_leaf=5729; feature_fraction=0.474; learning_rate=0.0694 : y = 0.929 : 57.4 secs : infill_ei

Tue Aug 12 2:43:41 PM 2025 AUC 0.920578285177144

[mbo] 5: num_leaves=2; min_data_in_leaf=5289; feature_fraction=0.899; learning_rate=0.0742 : y = 0.921 : 87.8 secs : infill_ei

Tue Aug 12 2:47:57 PM 2025 AUC 0.921280481572078

[mbo] 6: num_leaves=2; min_data_in_leaf=7123; feature_fraction=0.546; learning_rate=0.181 : y = 0.921 : 255.4 secs : infill_ei

Tue Aug 12 2:49:06 PM 2025 AUC 0.927931014107092

[mbo] 7: num_leaves=85; min_data_in_leaf=4369; feature_fraction=0.337; learning_rate=0.0667 : y = 0.928 : 68.9 secs : infill_ei

Tue Aug 12 2:54:32 PM 2025 AUC 0.921293216363426

[mbo] 8: num_leaves=2; min_data_in_leaf=5051; feature_fraction=0.385; learning_rate=0.0956 : y = 0.921 : 325.9 secs : infill_ei

Saved the current state after iteration 9 in the file HT.RDATA.

Tue Aug 12 2:55:02 PM 2025 AUC 0.927847898368894

[mbo] 9: num_leaves=40; min_data_in_leaf=6258; feature_fraction=0.804; learning_rate=0.137 : y = 0.928 : 29.8 secs : infill_ei

Tue Aug 12 2:56:24 PM 2025 AUC 0.926361238826919

[mbo] 10: num_leaves=129; min_data_in_leaf=3391; feature_fraction=0.258; learning_rate=0.0561 : y = 0.926 : 81.7 secs : infill_ei

Tue Aug 12 2:58:10 PM 2025 AUC 0.927593032744714

[mbo] 11: num_leaves=157; min_data_in_leaf=3972; feature_fraction=0.557; learning_rate=0.0576 : y = 0.928 : 105.3 secs : infill_ei

Tue Aug 12 2:59:25 PM 2025 AUC 0.925393139988637

[mbo] 12: num_leaves=168; min_data_in_leaf=3559; feature_fraction=0.742; learning_rate=0.147 : y = 0.925 : 75.2 secs : infill_ei

Tue Aug 12 3:00:25 PM 2025 AUC 0.929788256077297

[mbo] 13: num_leaves=45; min_data_in_leaf=6234; feature_fraction=0.402; learning_rate=0.0472 : y = 0.93 : 59.2 secs : infill_ei

Tue Aug 12 3:01:58 PM 2025 AUC 0.927619266414891

[mbo] 14: num_leaves=226; min_data_in_leaf=3839; feature_fraction=0.291; learning_rate=0.0387 : y = 0.928 : 93.0 secs : infill_ei

Tue Aug 12 3:03:02 PM 2025 AUC 0.931232805909215

[mbo] 15: num_leaves=60; min_data_in_leaf=3508; feature_fraction=0.473; learning_rate=0.0716 : y = 0.931 : 64.0 secs : infill_ei

Tue Aug 12 3:06:40 PM 2025 AUC 0.9300537340276

[mbo] 16: num_leaves=191; min_data_in_leaf=5723; feature_fraction=0.43; learning_rate=0.0102 : y = 0.93 : 217.7 secs : infill_ei

Saved the current state after iteration 17 in the file HT.RDATA.

Tue Aug 12 3:07:52 PM 2025 AUC 0.927377729872323

[mbo] 17: num_leaves=72; min_data_in_leaf=6511; feature_fraction=0.486; learning_rate=0.0552 : y = 0.927 : 71.3 secs : infill_ei

Tue Aug 12 3:09:06 PM 2025 AUC 0.927292576567509

[mbo] 18: num_leaves=193; min_data_in_leaf=5575; feature_fraction=0.367; learning_rate=0.119 : y = 0.927 : 74.6 secs : infill_ei

Tue Aug 12 3:13:26 PM 2025 AUC 0.92835032833688

[mbo] 19: num_leaves=256; min_data_in_leaf=2723; feature_fraction=0.549; learning_rate=0.01 : y = 0.928 : 259.2 secs : infill_ei

Tue Aug 12 3:16:01 PM 2025 AUC 0.929923499561414

[mbo] 20: num_leaves=195; min_data_in_leaf=8189; feature_fraction=0.208; learning_rate=0.01 : y = 0.93 : 155.0 secs : infill_ei

Saved the final state in the file HT.RDATA

la bayesian optimization ha corrido, extraigo los mejores hiperparametros

In [56]:
# almaceno los resultados de la Bayesian Optimization
# y capturo los mejores hiperparametros encontrados

tb_bayesiana <- as.data.table(bayesiana_salida$opt.path)

# ordeno en forma descendente por AUC = y
setorder(tb_bayesiana, -y, -num_iterations)

# grabo para eventualmente poder utilizarlos en OTRA corrida
fwrite( tb_bayesiana,
  file="BO_log.txt",
  sep="\t"
)

# los mejores hiperparámetros son los que quedaron en el registro 1 de la tabla
PARAM$out$lgbm$mejores_hiperparametros <- tb_bayesiana[
  1, # el primero es el de mejor AUC
  list(num_leaves, min_data_in_leaf, num_iterations)
]

print(PARAM$out$lgbm$mejores_hiperparametros)

   num_leaves min_data_in_leaf num_iterations
        <int>            <int>          <int>
1:         60             3508            225

### 9.3.3 Produccion

#### Final Training
Construyo el modelo final, que es uno solo, no hace ningun tipo de particion < training, validation, testing>]

##### Final Training Dataset

Aqui esta la gran decision de en qué meses hago el Final Training
<br> debo utilizar los mejores hiperparámetros que encontré en la optimización bayesiana

In [57]:
PARAM$trainingstrategy$final_train <- c(
  201901, 201902, 201903, 201904, 201905, 201906,
  201907, 201908, 201909, 201910, 201911, 201912,
  202001, 202002, 202003, 202004, 202005, 202006,
  202007, 202008, 202009, 202010, 202011, 202012,
  202101, 202102, 202103, 202104, 202105
)  # corregido para el grupo B

dataset[, fold_final_train := foto_mes %in% PARAM$trainingstrategy$final_train ]

# creo el dfinal_train en formato  LightGBM
dfinal_train <- lgb.Dataset(
  data= data.matrix(dataset[fold_final_train == TRUE, campos_buenos, with= FALSE]),
  label= dataset[fold_final_train == TRUE, clase01],
  free_raw_data= TRUE
)

nrow( dfinal_train) # verifico el tamaño

[1] 844168

##### Final Training Hyperparameters

In [58]:
# uno los parametros fijos y los mejores encontrados de los variables
fijos <- copy(PARAM$lgbm$param_fijos)

# quito lo que optimice en la Bayesian Optimization
fijos$num_iterations <- NULL
fijos$early_stopping_rounds <- NULL

# agrego a los hiperparametros fijos los que encontre con la Bayesian Optimization
param_final <- c(fijos, PARAM$out$lgbm$mejores_hiperparametros)

##### Training
Genero el modelo final, siempre sobre TODOS los datos de  final_train, sin hacer ningun tipo de undersampling de la clase mayoritaria

In [59]:
PARAM$FT$semillerio <- 20  # cantidad de semillas

In [60]:
if(!require("primes")) install.packages("primes")
require("primes")

Loading required package: primes

In [61]:
primos <- generate_primes(min = 100000, max = 1000000)
set.seed(PARAM$semilla_primigenia, kind = "L'Ecuyer-CMRG")
# me quedo con PARAM$semillerio  primos al azar
PARAM$FT$semillas <- sample(primos)[seq(PARAM$FT$semillerio)]

cat( PARAM$FT$semillas)

823591 119563 780799 800999 976211 378277 519067 557059 617387 761119 384533 172021 138113 969341 441157 333779 762659 172987 697979 118277

In [63]:
dir.create("modelos", showWarnings =FALSE)

primero <- TRUE
for( sem in PARAM$FT$semillas)
{
  nombre_arch <- paste0( "./modelos/modelo_", sem, ".txt")
  if( !file.exists(nombre_arch) )
  {
    param_final$seed <- sem

    set.seed(sem, kind = "L'Ecuyer-CMRG")
    final_model <- lgb.train(
      data= dfinal_train,
      param= param_final,
      verbose= -100
    )

    lgb.save(final_model, nombre_arch) # grabo el modelo"

    # grabo la primer importancia de variables
    #  Natalia : da lo mismo cual se guarda
    if( primero)
    {
      primero <- FALSE
      tb_importancia <- as.data.table(lgb.importance(final_model))
      archivo_importancia <- "impo.txt"

      fwrite( tb_importancia,
        file= archivo_importancia,
        sep= "\t"
      )
    }
 }
}

#### Scoring

Aplico el modelo final a los datos del futuro

In [64]:
PARAM$trainingstrategy$future <- c(202107) # ACÁ CAMBIAR LA FECHA PARA DATOS DEL FUTURO

dfuture <- dataset[ foto_mes %in% PARAM$trainingstrategy$future ]

In [65]:
# aplico final_model   a dfuture

tb_prediccion <- dfuture[, list(numero_de_cliente, clase_ternaria)] # modificado.
tb_prediccion[, prob := 0]

datos_matrix <- data.matrix(dfuture[, campos_buenos, with= FALSE])


for( isem in seq(length(PARAM$FT$semillas)) ) # Recorro cada semilla generada
{
   sem <- PARAM$FT$semillas[ isem ]
   nombre_arch <- paste0( "./modelos/modelo_", sem, ".txt") 
   final_model <- lgb.load(nombre_arch) # capturo el modelo construido con esa semilla
   # hago la prediccion con ese modelo 
   prediccion <- predict(
     final_model,
     datos_matrix
  )

  tb_prediccion[, paste0("prob_", isem) := prediccion]
  tb_prediccion[, prob := prob + prediccion]

  rm(final_model)
  rm(prediccion)
  gc(full = TRUE, verbose=FALSE)
}

rm( datos_matrix)
gc(full = TRUE, verbose=FALSE)

tb_prediccion[, prob := prob /length(PARAM$FT$semillas) ]

       used      (Mb)   gc trigger (Mb)    max used   (Mb)
Ncells   2657274  142.0    4163028   222.4    4163028   222.4
Vcells 939641117 7168.9 2940126358 22431.4 2940119369 22431.4

##### Tabla Prediccion

In [66]:
# veo que hay en tb_prediccion
tb_prediccion

# grabo las probabilidad del modelo
#  me va a ser util para hacer Ensembles de modelos
fwrite(tb_prediccion,
  file= "prediccion.txt",
  sep= "\t"
)

      numero_de_cliente clase_ternaria prob         prob_1       prob_2
1     29186441          CONTINUA       2.235774e-03 2.235774e-03 2.235774e-03
2     29187730          CONTINUA       1.400433e-04 1.400433e-04 1.400433e-04
3     29187961          CONTINUA       1.418172e-03 1.418172e-03 1.418172e-03
4     29193101          CONTINUA       1.548675e-03 1.548675e-03 1.548675e-03
5     29193281          CONTINUA       1.744897e-03 1.744897e-03 1.744897e-03
6     29198891          CONTINUA       5.059473e-04 5.059473e-04 5.059473e-04
7     29200651          CONTINUA       1.678504e-03 1.678504e-03 1.678504e-03
8     29200770          CONTINUA       5.976745e-05 5.976745e-05 5.976745e-05
9     29201701          CONTINUA       1.589493e-04 1.589493e-04 1.589493e-04
10    29205441          CONTINUA       5.599083e-02 5.599083e-02 5.599083e-02
11    29207790          CONTINUA       3.180546e-04 3.180546e-04 3.180546e-04
12    29207901          CONTINUA       1.110931e-03 1.110931e-03 1.110931e-03
13    29215330          CONTINUA       2.408330e-05 2.408330e-05 2.408330e-05
14    29217500          CONTINUA       4.717430e-04 4.717430e-04 4.717430e-04
15    29218080          CONTINUA       3.157931e-04 3.157931e-04 3.157931e-04
16    29219250          CONTINUA       2.139970e-04 2.139970e-04 2.139970e-04
17    29226090          CONTINUA       6.710411e-05 6.710411e-05 6.710411e-05
18    29229250          CONTINUA       5.096575e-03 5.096575e-03 5.096575e-03
19    29236620          CONTINUA       8.735495e-05 8.735495e-05 8.735495e-05
20    29243631          CONTINUA       1.320794e-04 1.320794e-04 1.320794e-04
21    29247850          CONTINUA       3.539487e-03 3.539487e-03 3.539487e-03
22    29251231          CONTINUA       8.610795e-05 8.610795e-05 8.610795e-05
23    29255740          CONTINUA       4.354243e-05 4.354243e-05 4.354243e-05
24    29257551          CONTINUA       2.741165e-04 2.741165e-04 2.741165e-04
25    29257790          CONTINUA       2.469774e-04 2.469774e-04 2.469774e-04
26    29267141          CONTINUA       1.444465e-04 1.444465e-04 1.444465e-04
27    29274460          CONTINUA       1.144383e-04 1.144383e-04 1.144383e-04
28    29277081          CONTINUA       2.671786e-03 2.671786e-03 2.671786e-03
29    29280480          CONTINUA       2.915961e-03 2.915961e-03 2.915961e-03
30    29280890          CONTINUA       1.555028e-02 1.555028e-02 1.555028e-02
⋮     ⋮                 ⋮              ⋮            ⋮            ⋮
33024 186892640         CONTINUA       0.0053116853 0.0053116853 0.0053116853
33025 186895100         CONTINUA       0.0222710358 0.0222710358 0.0222710358
33026 186896440         CONTINUA       0.0033686391 0.0033686391 0.0033686391
33027 186899651         CONTINUA       0.0022935594 0.0022935594 0.0022935594
33028 186903750         CONTINUA       0.0083889535 0.0083889535 0.0083889535
33029 186908200         CONTINUA       0.0022977227 0.0022977227 0.0022977227
33030 186908370         CONTINUA       0.0182574852 0.0182574852 0.0182574852
33031 186927790         CONTINUA       0.0082921880 0.0082921880 0.0082921880
33032 187003640         CONTINUA       0.0024019808 0.0024019808 0.0024019808
33033 187005740         CONTINUA       0.0053039744 0.0053039744 0.0053039744
33034 187021641         CONTINUA       0.0073817842 0.0073817842 0.0073817842
33035 187034750         CONTINUA       0.0007667174 0.0007667174 0.0007667174
33036 187060301         CONTINUA       0.0143992543 0.0143992543 0.0143992543
33037 187066091         CONTINUA       0.0049991844 0.0049991844 0.0049991844
33038 187090600         CONTINUA       0.0022352842 0.0022352842 0.0022352842
33039 187112590         CONTINUA       0.0029394047 0.0029394047 0.0029394047
33040 187146100         CONTINUA       0.0124863061 0.0124863061 0.0124863061
33041 187147620         CONTINUA       0.0714128388 0.0714128388 0.0714128388
33042 187170651         CONTINUA       0.0027839708 0.0027839708 0.0027839708
33043 187199490         CONTINUA       0.0107389475 0.0107389475 0.0107389475
33044 187203931         CONTINUA       0.0047627791 0.0047627791 0.0047627791
33045 187269951         CONTINUA       0.0047827183 0.0047827183 0.0047827183
33046 187272641         CONTINUA       0.0289622816 0.0289622816 0.0289622816
33047 187314281         CONTINUA       0.0049774934 0.0049774934 0.0049774934
33048 187346211         CONTINUA       0.0296924215 0.0296924215 0.0296924215
33049 187366971         BAJA+1         0.0177829314 0.0177829314 0.0177829314
33050 187402240         CONTINUA       0.0372944793 0.0372944793 0.0372944793
33051 187429081         CONTINUA       0.0042721063 0.0042721063 0.0042721063
33052 187434871         CONTINUA       0.0355465242 0.0355465242 0.0355465242
33053 187444350         CONTINUA       0.0371418907 0.0371418907 0.0371418907
      prob_3       prob_4       prob_5       prob_6       prob_7       ⋯
1     2.235774e-03 2.235774e-03 2.235774e-03 2.235774e-03 2.235774e-03 ⋯
2     1.400433e-04 1.400433e-04 1.400433e-04 1.400433e-04 1.400433e-04 ⋯
3     1.418172e-03 1.418172e-03 1.418172e-03 1.418172e-03 1.418172e-03 ⋯
4     1.548675e-03 1.548675e-03 1.548675e-03 1.548675e-03 1.548675e-03 ⋯
5     1.744897e-03 1.744897e-03 1.744897e-03 1.744897e-03 1.744897e-03 ⋯
6     5.059473e-04 5.059473e-04 5.059473e-04 5.059473e-04 5.059473e-04 ⋯
7     1.678504e-03 1.678504e-03 1.678504e-03 1.678504e-03 1.678504e-03 ⋯
8     5.976745e-05 5.976745e-05 5.976745e-05 5.976745e-05 5.976745e-05 ⋯
9     1.589493e-04 1.589493e-04 1.589493e-04 1.589493e-04 1.589493e-04 ⋯
10    5.599083e-02 5.599083e-02 5.599083e-02 5.599083e-02 5.599083e-02 ⋯
11    3.180546e-04 3.180546e-04 3.180546e-04 3.180546e-04 3.180546e-04 ⋯
12    1.110931e-03 1.110931e-03 1.110931e-03 1.110931e-03 1.110931e-03 ⋯
13    2.408330e-05 2.408330e-05 2.408330e-05 2.408330e-05 2.408330e-05 ⋯
14    4.717430e-04 4.717430e-04 4.717430e-04 4.717430e-04 4.717430e-04 ⋯
15    3.157931e-04 3.157931e-04 3.157931e-04 3.157931e-04 3.157931e-04 ⋯
16    2.139970e-04 2.139970e-04 2.139970e-04 2.139970e-04 2.139970e-04 ⋯
17    6.710411e-05 6.710411e-05 6.710411e-05 6.710411e-05 6.710411e-05 ⋯
18    5.096575e-03 5.096575e-03 5.096575e-03 5.096575e-03 5.096575e-03 ⋯
19    8.735495e-05 8.735495e-05 8.735495e-05 8.735495e-05 8.735495e-05 ⋯
20    1.320794e-04 1.320794e-04 1.320794e-04 1.320794e-04 1.320794e-04 ⋯
21    3.539487e-03 3.539487e-03 3.539487e-03 3.539487e-03 3.539487e-03 ⋯
22    8.610795e-05 8.610795e-05 8.610795e-05 8.610795e-05 8.610795e-05 ⋯
23    4.354243e-05 4.354243e-05 4.354243e-05 4.354243e-05 4.354243e-05 ⋯
24    2.741165e-04 2.741165e-04 2.741165e-04 2.741165e-04 2.741165e-04 ⋯
25    2.469774e-04 2.469774e-04 2.469774e-04 2.469774e-04 2.469774e-04 ⋯
26    1.444465e-04 1.444465e-04 1.444465e-04 1.444465e-04 1.444465e-04 ⋯
27    1.144383e-04 1.144383e-04 1.144383e-04 1.144383e-04 1.144383e-04 ⋯
28    2.671786e-03 2.671786e-03 2.671786e-03 2.671786e-03 2.671786e-03 ⋯
29    2.915961e-03 2.915961e-03 2.915961e-03 2.915961e-03 2.915961e-03 ⋯
30    1.555028e-02 1.555028e-02 1.555028e-02 1.555028e-02 1.555028e-02 ⋯
⋮     ⋮            ⋮            ⋮            ⋮            ⋮            ⋱
33024 0.0053116853 0.0053116853 0.0053116853 0.0053116853 0.0053116853 ⋯
33025 0.0222710358 0.0222710358 0.0222710358 0.0222710358 0.0222710358 ⋯
33026 0.0033686391 0.0033686391 0.0033686391 0.0033686391 0.0033686391 ⋯
33027 0.0022935594 0.0022935594 0.0022935594 0.0022935594 0.0022935594 ⋯
33028 0.0083889535 0.0083889535 0.0083889535 0.0083889535 0.0083889535 ⋯
33029 0.0022977227 0.0022977227 0.0022977227 0.0022977227 0.0022977227 ⋯
33030 0.0182574852 0.0182574852 0.0182574852 0.0182574852 0.0182574852 ⋯
33031 0.0082921880 0.0082921880 0.0082921880 0.0082921880 0.0082921880 ⋯
33032 0.0024019808 0.0024019808 0.0024019808 0.0024019808 0.0024019808 ⋯
33033 0.0053039744 0.0053039744 0.0053039744 0.0053039744 0.0053039744 ⋯
33034 0.0073817842 0.0073817842 0.0073817842 0.0073817842 0.0073817842 ⋯
33035 0.0007667174 0.0007667174 0.0007667174 0.0007667174 0.0007667174 ⋯
33036 0.0143992543 0.0143992543 0.0143992543 0.0143992543 0.0143992543 ⋯
33037 0.0049991844 0.0049991844 0.0049991844 0.0049991844 0.0049991844 ⋯
33038 0.0022352842 0.0022352842 0.0022352842 0.0022352842 0.0022352842 ⋯
33039 0.0029394047 0.0029394047 0.0029394047 0.0029394047 0.0029394047 ⋯
33040 0.0124863061 0.0124863061 0.0124863061 0.0124863061 0.0124863061 ⋯
33041 0.0714128388 0.0714128388 0.0714128388 0.0714128388 0.0714128388 ⋯
33042 0.0027839708 0.0027839708 0.0027839708 0.0027839708 0.0027839708 ⋯
33043 0.0107389475 0.0107389475 0.0107389475 0.0107389475 0.0107389475 ⋯
33044 0.0047627791 0.0047627791 0.0047627791 0.0047627791 0.0047627791 ⋯
33045 0.0047827183 0.0047827183 0.0047827183 0.0047827183 0.0047827183 ⋯
33046 0.0289622816 0.0289622816 0.0289622816 0.0289622816 0.0289622816 ⋯
33047 0.0049774934 0.0049774934 0.0049774934 0.0049774934 0.0049774934 ⋯
33048 0.0296924215 0.0296924215 0.0296924215 0.0296924215 0.0296924215 ⋯
33049 0.0177829314 0.0177829314 0.0177829314 0.0177829314 0.0177829314 ⋯
33050 0.0372944793 0.0372944793 0.0372944793 0.0372944793 0.0372944793 ⋯
33051 0.0042721063 0.0042721063 0.0042721063 0.0042721063 0.0042721063 ⋯
33052 0.0355465242 0.0355465242 0.0355465242 0.0355465242 0.0355465242 ⋯
33053 0.0371418907 0.0371418907 0.0371418907 0.0371418907 0.0371418907 ⋯
      prob_11      prob_12      prob_13      prob_14      prob_15
1     2.235774e-03 2.235774e-03 2.235774e-03 2.235774e-03 2.235774e-03
2     1.400433e-04 1.400433e-04 1.400433e-04 1.400433e-04 1.400433e-04
3     1.418172e-03 1.418172e-03 1.418172e-03 1.418172e-03 1.418172e-03
4     1.548675e-03 1.548675e-03 1.548675e-03 1.548675e-03 1.548675e-03
5     1.744897e-03 1.744897e-03 1.744897e-03 1.744897e-03 1.744897e-03
6     5.059473e-04 5.059473e-04 5.059473e-04 5.059473e-04 5.059473e-04
7     1.678504e-03 1.678504e-03 1.678504e-03 1.678504e-03 1.678504e-03
8     5.976745e-05 5.976745e-05 5.976745e-05 5.976745e-05 5.976745e-05
9     1.589493e-04 1.589493e-04 1.589493e-04 1.589493e-04 1.589493e-04
10    5.599083e-02 5.599083e-02 5.599083e-02 5.599083e-02 5.599083e-02
11    3.180546e-04 3.180546e-04 3.180546e-04 3.180546e-04 3.180546e-04
12    1.110931e-03 1.110931e-03 1.110931e-03 1.110931e-03 1.110931e-03
13    2.408330e-05 2.408330e-05 2.408330e-05 2.408330e-05 2.408330e-05
14    4.717430e-04 4.717430e-04 4.717430e-04 4.717430e-04 4.717430e-04
15    3.157931e-04 3.157931e-04 3.157931e-04 3.157931e-04 3.157931e-04
16    2.139970e-04 2.139970e-04 2.139970e-04 2.139970e-04 2.139970e-04
17    6.710411e-05 6.710411e-05 6.710411e-05 6.710411e-05 6.710411e-05
18    5.096575e-03 5.096575e-03 5.096575e-03 5.096575e-03 5.096575e-03
19    8.735495e-05 8.735495e-05 8.735495e-05 8.735495e-05 8.735495e-05
20    1.320794e-04 1.320794e-04 1.320794e-04 1.320794e-04 1.320794e-04
21    3.539487e-03 3.539487e-03 3.539487e-03 3.539487e-03 3.539487e-03
22    8.610795e-05 8.610795e-05 8.610795e-05 8.610795e-05 8.610795e-05
23    4.354243e-05 4.354243e-05 4.354243e-05 4.354243e-05 4.354243e-05
24    2.741165e-04 2.741165e-04 2.741165e-04 2.741165e-04 2.741165e-04
25    2.469774e-04 2.469774e-04 2.469774e-04 2.469774e-04 2.469774e-04
26    1.444465e-04 1.444465e-04 1.444465e-04 1.444465e-04 1.444465e-04
27    1.144383e-04 1.144383e-04 1.144383e-04 1.144383e-04 1.144383e-04
28    2.671786e-03 2.671786e-03 2.671786e-03 2.671786e-03 2.671786e-03
29    2.915961e-03 2.915961e-03 2.915961e-03 2.915961e-03 2.915961e-03
30    1.555028e-02 1.555028e-02 1.555028e-02 1.555028e-02 1.555028e-02
⋮     ⋮            ⋮            ⋮            ⋮            ⋮
33024 0.0053116853 0.0053116853 0.0053116853 0.0053116853 0.0053116853
33025 0.0222710358 0.0222710358 0.0222710358 0.0222710358 0.0222710358
33026 0.0033686391 0.0033686391 0.0033686391 0.0033686391 0.0033686391
33027 0.0022935594 0.0022935594 0.0022935594 0.0022935594 0.0022935594
33028 0.0083889535 0.0083889535 0.0083889535 0.0083889535 0.0083889535
33029 0.0022977227 0.0022977227 0.0022977227 0.0022977227 0.0022977227
33030 0.0182574852 0.0182574852 0.0182574852 0.0182574852 0.0182574852
33031 0.0082921880 0.0082921880 0.0082921880 0.0082921880 0.0082921880
33032 0.0024019808 0.0024019808 0.0024019808 0.0024019808 0.0024019808
33033 0.0053039744 0.0053039744 0.0053039744 0.0053039744 0.0053039744
33034 0.0073817842 0.0073817842 0.0073817842 0.0073817842 0.0073817842
33035 0.0007667174 0.0007667174 0.0007667174 0.0007667174 0.0007667174
33036 0.0143992543 0.0143992543 0.0143992543 0.0143992543 0.0143992543
33037 0.0049991844 0.0049991844 0.0049991844 0.0049991844 0.0049991844
33038 0.0022352842 0.0022352842 0.0022352842 0.0022352842 0.0022352842
33039 0.0029394047 0.0029394047 0.0029394047 0.0029394047 0.0029394047
33040 0.0124863061 0.0124863061 0.0124863061 0.0124863061 0.0124863061
33041 0.0714128388 0.0714128388 0.0714128388 0.0714128388 0.0714128388
33042 0.0027839708 0.0027839708 0.0027839708 0.0027839708 0.0027839708
33043 0.0107389475 0.0107389475 0.0107389475 0.0107389475 0.0107389475
33044 0.0047627791 0.0047627791 0.0047627791 0.0047627791 0.0047627791
33045 0.0047827183 0.0047827183 0.0047827183 0.0047827183 0.0047827183
33046 0.0289622816 0.0289622816 0.0289622816 0.0289622816 0.0289622816
33047 0.0049774934 0.0049774934 0.0049774934 0.0049774934 0.0049774934
33048 0.0296924215 0.0296924215 0.0296924215 0.0296924215 0.0296924215
33049 0.0177829314 0.0177829314 0.0177829314 0.0177829314 0.0177829314
33050 0.0372944793 0.0372944793 0.0372944793 0.0372944793 0.0372944793
33051 0.0042721063 0.0042721063 0.0042721063 0.0042721063 0.0042721063
33052 0.0355465242 0.0355465242 0.0355465242 0.0355465242 0.0355465242
33053 0.0371418907 0.0371418907 0.0371418907 0.0371418907 0.0371418907
      prob_16      prob_17      prob_18      prob_19      prob_20
1     2.235774e-03 2.235774e-03 2.235774e-03 2.235774e-03 2.235774e-03
2     1.400433e-04 1.400433e-04 1.400433e-04 1.400433e-04 1.400433e-04
3     1.418172e-03 1.418172e-03 1.418172e-03 1.418172e-03 1.418172e-03
4     1.548675e-03 1.548675e-03 1.548675e-03 1.548675e-03 1.548675e-03
5     1.744897e-03 1.744897e-03 1.744897e-03 1.744897e-03 1.744897e-03
6     5.059473e-04 5.059473e-04 5.059473e-04 5.059473e-04 5.059473e-04
7     1.678504e-03 1.678504e-03 1.678504e-03 1.678504e-03 1.678504e-03
8     5.976745e-05 5.976745e-05 5.976745e-05 5.976745e-05 5.976745e-05
9     1.589493e-04 1.589493e-04 1.589493e-04 1.589493e-04 1.589493e-04
10    5.599083e-02 5.599083e-02 5.599083e-02 5.599083e-02 5.599083e-02
11    3.180546e-04 3.180546e-04 3.180546e-04 3.180546e-04 3.180546e-04
12    1.110931e-03 1.110931e-03 1.110931e-03 1.110931e-03 1.110931e-03
13    2.408330e-05 2.408330e-05 2.408330e-05 2.408330e-05 2.408330e-05
14    4.717430e-04 4.717430e-04 4.717430e-04 4.717430e-04 4.717430e-04
15    3.157931e-04 3.157931e-04 3.157931e-04 3.157931e-04 3.157931e-04
16    2.139970e-04 2.139970e-04 2.139970e-04 2.139970e-04 2.139970e-04
17    6.710411e-05 6.710411e-05 6.710411e-05 6.710411e-05 6.710411e-05
18    5.096575e-03 5.096575e-03 5.096575e-03 5.096575e-03 5.096575e-03
19    8.735495e-05 8.735495e-05 8.735495e-05 8.735495e-05 8.735495e-05
20    1.320794e-04 1.320794e-04 1.320794e-04 1.320794e-04 1.320794e-04
21    3.539487e-03 3.539487e-03 3.539487e-03 3.539487e-03 3.539487e-03
22    8.610795e-05 8.610795e-05 8.610795e-05 8.610795e-05 8.610795e-05
23    4.354243e-05 4.354243e-05 4.354243e-05 4.354243e-05 4.354243e-05
24    2.741165e-04 2.741165e-04 2.741165e-04 2.741165e-04 2.741165e-04
25    2.469774e-04 2.469774e-04 2.469774e-04 2.469774e-04 2.469774e-04
26    1.444465e-04 1.444465e-04 1.444465e-04 1.444465e-04 1.444465e-04
27    1.144383e-04 1.144383e-04 1.144383e-04 1.144383e-04 1.144383e-04
28    2.671786e-03 2.671786e-03 2.671786e-03 2.671786e-03 2.671786e-03
29    2.915961e-03 2.915961e-03 2.915961e-03 2.915961e-03 2.915961e-03
30    1.555028e-02 1.555028e-02 1.555028e-02 1.555028e-02 1.555028e-02
⋮     ⋮            ⋮            ⋮            ⋮            ⋮
33024 0.0053116853 0.0053116853 0.0053116853 0.0053116853 0.0053116853
33025 0.0222710358 0.0222710358 0.0222710358 0.0222710358 0.0222710358
33026 0.0033686391 0.0033686391 0.0033686391 0.0033686391 0.0033686391
33027 0.0022935594 0.0022935594 0.0022935594 0.0022935594 0.0022935594
33028 0.0083889535 0.0083889535 0.0083889535 0.0083889535 0.0083889535
33029 0.0022977227 0.0022977227 0.0022977227 0.0022977227 0.0022977227
33030 0.0182574852 0.0182574852 0.0182574852 0.0182574852 0.0182574852
33031 0.0082921880 0.0082921880 0.0082921880 0.0082921880 0.0082921880
33032 0.0024019808 0.0024019808 0.0024019808 0.0024019808 0.0024019808
33033 0.0053039744 0.0053039744 0.0053039744 0.0053039744 0.0053039744
33034 0.0073817842 0.0073817842 0.0073817842 0.0073817842 0.0073817842
33035 0.0007667174 0.0007667174 0.0007667174 0.0007667174 0.0007667174
33036 0.0143992543 0.0143992543 0.0143992543 0.0143992543 0.0143992543
33037 0.0049991844 0.0049991844 0.0049991844 0.0049991844 0.0049991844
33038 0.0022352842 0.0022352842 0.0022352842 0.0022352842 0.0022352842
33039 0.0029394047 0.0029394047 0.0029394047 0.0029394047 0.0029394047
33040 0.0124863061 0.0124863061 0.0124863061 0.0124863061 0.0124863061
33041 0.0714128388 0.0714128388 0.0714128388 0.0714128388 0.0714128388
33042 0.0027839708 0.0027839708 0.0027839708 0.0027839708 0.0027839708
33043 0.0107389475 0.0107389475 0.0107389475 0.0107389475 0.0107389475
33044 0.0047627791 0.0047627791 0.0047627791 0.0047627791 0.0047627791
33045 0.0047827183 0.0047827183 0.0047827183 0.0047827183 0.0047827183
33046 0.0289622816 0.0289622816 0.0289622816 0.0289622816 0.0289622816
33047 0.0049774934 0.0049774934 0.0049774934 0.0049774934 0.0049774934
33048 0.0296924215 0.0296924215 0.0296924215 0.0296924215 0.0296924215
33049 0.0177829314 0.0177829314 0.0177829314 0.0177829314 0.0177829314
33050 0.0372944793 0.0372944793 0.0372944793 0.0372944793 0.0372944793
33051 0.0042721063 0.0042721063 0.0042721063 0.0042721063 0.0042721063
33052 0.0355465242 0.0355465242 0.0355465242 0.0355465242 0.0355465242
33053 0.0371418907 0.0371418907 0.0371418907 0.0371418907 0.0371418907

In [67]:
setorder(tb_prediccion, -prob)
top_2400 <- tb_prediccion[1:2400]

In [ ]:
library(data.table)
library(ggplot2)
library(scales)  # para formatear ejes

# Ordenar por probabilidad descendente
setorder(tb_prediccion, -prob)

# Rango de k hasta 2400
valores_k <- seq(1800, 2400, by = 100)


# Calcular ganancia para cada k
resultados <- data.table(k = valores_k)
resultados[, ganancia := sapply(k, function(topk) {
  top_k <- tb_prediccion[1:topk]
  top_k[, ganancia := ifelse(clase_ternaria == "BAJA+2", 117000, -3000)]
  sum(top_k$ganancia)
})]

# Graficar curva de ganancia con eje Y en miles
ggplot(resultados, aes(x = k, y = ganancia)) +
  geom_line(color = "steelblue", size = 1) +
  geom_point(color = "darkred") +
  geom_vline(xintercept = 2200, linetype = "dashed", color = "gray50") +
  scale_y_continuous(labels = label_number(scale = 1/1000, suffix = " K")) +
  labs(
    title = "Curva de Ganancia Acumulada (Analista Junior)",
    x = "Cantidad de envíos (k)",
    y = "Ganancia acumulada (miles)"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12)
  )

  BAJA+1   BAJA+2 CONTINUA
     179      161     2060

In [ ]:
library(data.table)

# Ordenar por probabilidad descendente
setorder(tb_prediccion, -prob)

# Definir k (máximo)
k <- min(#NRO#, nrow(tb_prediccion))

# Seleccionar las primeras k filas
top_k <- tb_prediccion[1:k]

# Calcular ganancia
ganancia <- sum(ifelse(top_k$clase_ternaria == "BAJA+2", 117000, -3000))

# Formatear con separador de miles y coma decimal
ganancia_formateada <- format(
  round(ganancia, 2),
  big.mark = ".",
  decimal.mark = ",",
  nsmall = 2
)

# Conteos por clase
conteos <- top_k[, .N, by = clase_ternaria]

# Mostrar
cat("Ganancia total:", ganancia_formateada, "\n")
print(conteos)

[1] 12120000

  clase_ternaria N
1 BAJA+1          179
2 CONTINUA       2060
3 BAJA+2          161

In [74]:
# grabo los parametros
if( !require("yaml")) install.packages("yaml")
require("yaml")

write_yaml( PARAM, file="PARAM.yml")

Loading required package: yaml

In [75]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Tue Aug 12 2:01:49 AM 2025"